/**
 * FactSet SCIM API
 * FactSet's SCIM API implementation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupResourceMembers model module.
 * @module model/GroupResourceMembers
 * @version 0.20.1
 */
class GroupResourceMembers {
    /**
     * Constructs a new <code>GroupResourceMembers</code>.
     * @alias module:model/GroupResourceMembers
     */
    constructor() { 
        
        GroupResourceMembers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupResourceMembers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupResourceMembers} obj Optional instance to populate.
     * @return {module:model/GroupResourceMembers} The populated <code>GroupResourceMembers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupResourceMembers();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('$ref')) {
                obj['$ref'] = ApiClient.convertToType(data['$ref'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Identifier of the member of this Group.
 * @member {String} value
 */
GroupResourceMembers.prototype['value'] = undefined;

/**
 * The URI corresponding to a SCIM resource that is a member of this Group.
 * @member {String} $ref
 */
GroupResourceMembers.prototype['$ref'] = undefined;

/**
 * A label indicating the type of resource, e.g., 'User' or 'Group'.
 * @member {String} type
 */
GroupResourceMembers.prototype['type'] = undefined;






export default GroupResourceMembers;

