/*
 * GIPS API
 * Allow clients to use GIPS through APIs.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.factset.sdk.GIPS.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.factset.sdk.GIPS.JSON;


/**
 * FactSetProtobufStachV3SortColumn
 */
@JsonPropertyOrder({
  FactSetProtobufStachV3SortColumn.JSON_PROPERTY_BY,
  FactSetProtobufStachV3SortColumn.JSON_PROPERTY_DESCENDING,
  FactSetProtobufStachV3SortColumn.JSON_PROPERTY_NULLS_FIRST,
  FactSetProtobufStachV3SortColumn.JSON_PROPERTY_CASE_INSENSITIVE,
  FactSetProtobufStachV3SortColumn.JSON_PROPERTY_ABSOLUTE_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class FactSetProtobufStachV3SortColumn implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BY = "by";
  private JsonNullable<String> by = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCENDING = "descending";
  private Boolean descending;

  public static final String JSON_PROPERTY_NULLS_FIRST = "nullsFirst";
  private Boolean nullsFirst;

  public static final String JSON_PROPERTY_CASE_INSENSITIVE = "caseInsensitive";
  private Boolean caseInsensitive;

  public static final String JSON_PROPERTY_ABSOLUTE_VALUE = "absoluteValue";
  private Boolean absoluteValue;

  public FactSetProtobufStachV3SortColumn() { 
  }

  public FactSetProtobufStachV3SortColumn by(String by) {
    this.by = JsonNullable.<String>of(by);
    return this;
  }

   /**
   * Get by
   * @return by
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getBy() {
        return by.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBy_JsonNullable() {
    return by;
  }
  
  @JsonProperty(JSON_PROPERTY_BY)
  public void setBy_JsonNullable(JsonNullable<String> by) {
    this.by = by;
  }

  public void setBy(String by) {
    this.by = JsonNullable.<String>of(by);
  }


  public FactSetProtobufStachV3SortColumn descending(Boolean descending) {
    this.descending = descending;
    return this;
  }

   /**
   * Get descending
   * @return descending
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCENDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDescending() {
    return descending;
  }


  @JsonProperty(JSON_PROPERTY_DESCENDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescending(Boolean descending) {
    this.descending = descending;
  }


  public FactSetProtobufStachV3SortColumn nullsFirst(Boolean nullsFirst) {
    this.nullsFirst = nullsFirst;
    return this;
  }

   /**
   * Get nullsFirst
   * @return nullsFirst
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NULLS_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNullsFirst() {
    return nullsFirst;
  }


  @JsonProperty(JSON_PROPERTY_NULLS_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNullsFirst(Boolean nullsFirst) {
    this.nullsFirst = nullsFirst;
  }


  public FactSetProtobufStachV3SortColumn caseInsensitive(Boolean caseInsensitive) {
    this.caseInsensitive = caseInsensitive;
    return this;
  }

   /**
   * Get caseInsensitive
   * @return caseInsensitive
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CASE_INSENSITIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCaseInsensitive() {
    return caseInsensitive;
  }


  @JsonProperty(JSON_PROPERTY_CASE_INSENSITIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaseInsensitive(Boolean caseInsensitive) {
    this.caseInsensitive = caseInsensitive;
  }


  public FactSetProtobufStachV3SortColumn absoluteValue(Boolean absoluteValue) {
    this.absoluteValue = absoluteValue;
    return this;
  }

   /**
   * Get absoluteValue
   * @return absoluteValue
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ABSOLUTE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAbsoluteValue() {
    return absoluteValue;
  }


  @JsonProperty(JSON_PROPERTY_ABSOLUTE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAbsoluteValue(Boolean absoluteValue) {
    this.absoluteValue = absoluteValue;
  }


  /**
   * Return true if this FactSet.Protobuf.Stach.V3.SortColumn object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactSetProtobufStachV3SortColumn factSetProtobufStachV3SortColumn = (FactSetProtobufStachV3SortColumn) o;
    return equalsNullable(this.by, factSetProtobufStachV3SortColumn.by) &&
        Objects.equals(this.descending, factSetProtobufStachV3SortColumn.descending) &&
        Objects.equals(this.nullsFirst, factSetProtobufStachV3SortColumn.nullsFirst) &&
        Objects.equals(this.caseInsensitive, factSetProtobufStachV3SortColumn.caseInsensitive) &&
        Objects.equals(this.absoluteValue, factSetProtobufStachV3SortColumn.absoluteValue);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(by), descending, nullsFirst, caseInsensitive, absoluteValue);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactSetProtobufStachV3SortColumn {\n");
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("    descending: ").append(toIndentedString(descending)).append("\n");
    sb.append("    nullsFirst: ").append(toIndentedString(nullsFirst)).append("\n");
    sb.append("    caseInsensitive: ").append(toIndentedString(caseInsensitive)).append("\n");
    sb.append("    absoluteValue: ").append(toIndentedString(absoluteValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

