/**
 * FactSet Overview Report Builder API
 * Get relevant industry-specific data for high level analysis of public and private companies
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KeyStatsAttributeLabel from './KeyStatsAttributeLabel';
import KeyStatsDataObjectEntityExDividendDateValue from './KeyStatsDataObjectEntityExDividendDateValue';

/**
 * The KeyStatsDataObjectEntityFirstDate model module.
 * @module model/KeyStatsDataObjectEntityFirstDate
 */
class KeyStatsDataObjectEntityFirstDate {
    /**
     * Constructs a new <code>KeyStatsDataObjectEntityFirstDate</code>.
     * The day on which a private company&#39;s shares became available for purchase by the public for the first time
     * @alias module:model/KeyStatsDataObjectEntityFirstDate
     * @param label {module:model/KeyStatsAttributeLabel} 
     * @param value {module:model/KeyStatsDataObjectEntityExDividendDateValue} 
     */
    constructor(label, value) { 
        
        KeyStatsDataObjectEntityFirstDate.initialize(this, label, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, label, value) { 
        obj['label'] = label;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>KeyStatsDataObjectEntityFirstDate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KeyStatsDataObjectEntityFirstDate} obj Optional instance to populate.
     * @return {module:model/KeyStatsDataObjectEntityFirstDate} The populated <code>KeyStatsDataObjectEntityFirstDate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KeyStatsDataObjectEntityFirstDate();

            if (data.hasOwnProperty('label')) {
                obj['label'] = KeyStatsAttributeLabel.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = KeyStatsDataObjectEntityExDividendDateValue.constructFromObject(data['value']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/KeyStatsAttributeLabel} label
 */
KeyStatsDataObjectEntityFirstDate.prototype['label'] = undefined;

/**
 * @member {module:model/KeyStatsDataObjectEntityExDividendDateValue} value
 */
KeyStatsDataObjectEntityFirstDate.prototype['value'] = undefined;






export default KeyStatsDataObjectEntityFirstDate;

