/**
 * FactSet RBICS
 * FactSet Revere Business Industry Classification System (RBICS) is a comprehensive structured taxonomy to classify companies by what they primarily do. It delivers a granular view for investors by classifying companies using a bottom-up approach according to the products and services they provide. By combining this approach with a top-level grouping based on companies' behavior similarities and stock co-movement, FactSet RBICS delivers unprecedented precision for 1,400+ sector groups.  RBICS Focus is a six level classification which highlights the companys main business. It is based on the company business line/s that stand for majority of a the revenue that the company generates. Updated monthly. For more details, visit [Online Assistant Page #20710](https://oa.apps.factset.com/pages/20710).<p><b>Rate limit is set to 10 requests per second</b>.</p> 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EntityFocusRequest from '../model/EntityFocusRequest';
import EntityFocusResponse from '../model/EntityFocusResponse';
import EntityRequest from '../model/EntityRequest';
import EntityResponse from '../model/EntityResponse';
import ErrorResponse from '../model/ErrorResponse';
import ErrorsResponse from '../model/ErrorsResponse';

/**
* Entity service.
* @module api/EntityApi
*/
export default class EntityApi {

    /**
    * Constructs a new EntityApi. 
    * @alias module:api/EntityApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get RBICS classification for the Focus industry
     * Gets RBICS classifications for the Focus industry for a short list of companies. Full history is included if _date_ parameter is not specified.    RBICS Focus offers a single-sector mapping of about 48,000 of the most liquid and publicly-traded companies based on their primary lines of business; it uses revenues as the key factor in determining a company’s primary line of business, by mapping a company to the lowest-level sector from which it derives 50% or more of its revenues.    The RBICS Extended Universe – Industry Group is not currently supported through the RBICS API. 
     * @param {Array.<String>} ids List of Company identifiers. Accepted identifiers include Ticker-Exchange, Ticker-Regions, CUSIPs, ISINs, SEDOLs, or FactSet Permanent Ids, such as -R, -L, or -E.<p>**ids limit = 2500 per request**</p>    Make note, GET Method URL request lines are also limited to a total length of 8192 bytes (8KB). In cases where the service allows for thousands of ids, which may lead to exceeding this request line limit of 8KB, its advised for any requests with large request lines to be requested through the respective \"POST\" method.</p> 
     * @param {Object} opts Optional parameters
     * @param {String} opts.date Effective date for data expressed in YYYY-MM-DD format. If no date is requested, the default behavior is to return the full history for the requested entity.
     * @param {Array.<Number>} opts.levels List of RBICS industry levels to include in the response. **By default if left blank, all levels are returned.**
     * @param {Boolean} opts.includeNames Option to include or exclude industry Names and the L6 Description. true = Include Names; false = Exclude Names. (default to true)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntityFocusResponse} and HTTP response
     */
    getRbicsEntityFocusWithHttpInfo(ids, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling getRbicsEntityFocus");
      }

      let pathParams = {
      };
      let queryParams = {
        'ids': this.apiClient.buildCollectionParam(ids, 'csv'),
        'date': opts['date'],
        'levels': this.apiClient.buildCollectionParam(opts['levels'], 'csv'),
        'includeNames': opts['includeNames']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['FactSetApiKey', 'FactSetOAuth2'];
      let contentTypes = [];
      let accepts = ['application/json'];


      let returnType = EntityFocusResponse;

      return this.apiClient.callApi(
        '/factset-rbics/v1/entity-focus', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get RBICS classification for the Focus industry
     * Gets RBICS classifications for the Focus industry for a short list of companies. Full history is included if _date_ parameter is not specified.    RBICS Focus offers a single-sector mapping of about 48,000 of the most liquid and publicly-traded companies based on their primary lines of business; it uses revenues as the key factor in determining a company’s primary line of business, by mapping a company to the lowest-level sector from which it derives 50% or more of its revenues.    The RBICS Extended Universe – Industry Group is not currently supported through the RBICS API. 
     * @param {Array.<String>} ids List of Company identifiers. Accepted identifiers include Ticker-Exchange, Ticker-Regions, CUSIPs, ISINs, SEDOLs, or FactSet Permanent Ids, such as -R, -L, or -E.<p>**ids limit = 2500 per request**</p>    Make note, GET Method URL request lines are also limited to a total length of 8192 bytes (8KB). In cases where the service allows for thousands of ids, which may lead to exceeding this request line limit of 8KB, its advised for any requests with large request lines to be requested through the respective \"POST\" method.</p> 
     * @param {Object} opts Optional parameters
     * @param {String} opts.date Effective date for data expressed in YYYY-MM-DD format. If no date is requested, the default behavior is to return the full history for the requested entity.
     * @param {Array.<Number>} opts.levels List of RBICS industry levels to include in the response. **By default if left blank, all levels are returned.**
     * @param {Boolean} opts.includeNames Option to include or exclude industry Names and the L6 Description. true = Include Names; false = Exclude Names. (default to true)
     * @return { Promise.< module:model/EntityFocusResponse > } a Promise, with data of type {@link module:model/EntityFocusResponse }
     */
    getRbicsEntityFocus(ids, opts) {
      return this.getRbicsEntityFocusWithHttpInfo(ids, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get RBICS classification for the Focus industry
     * Gets RBICS classifications for the Focus industry for a long list of companies. Full history is included if _date_ parameter is not specified.    RBICS Focus offers a single-sector mapping of about 48,000 of the most liquid and publicly-traded companies based on their primary lines of business; it uses revenues as the key factor in determining a company’s primary line of business, by mapping a company to the lowest-level sector from which it derives 50% or more of its revenues.    The RBICS Extended Universe – Industry Group is not currently supported through the RBICS API. 
     * @param {module:model/EntityFocusRequest} entityFocusRequest Request Body to request a list of RBICS Entity Focus objects.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntityFocusResponse} and HTTP response
     */
    getRbicsEntityFocusForListWithHttpInfo(entityFocusRequest) {
      let postBody = entityFocusRequest;
      // verify the required parameter 'entityFocusRequest' is set
      if (entityFocusRequest === undefined || entityFocusRequest === null) {
        throw new Error("Missing the required parameter 'entityFocusRequest' when calling getRbicsEntityFocusForList");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['FactSetApiKey', 'FactSetOAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];


      let returnType = EntityFocusResponse;

      return this.apiClient.callApi(
        '/factset-rbics/v1/entity-focus', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get RBICS classification for the Focus industry
     * Gets RBICS classifications for the Focus industry for a long list of companies. Full history is included if _date_ parameter is not specified.    RBICS Focus offers a single-sector mapping of about 48,000 of the most liquid and publicly-traded companies based on their primary lines of business; it uses revenues as the key factor in determining a company’s primary line of business, by mapping a company to the lowest-level sector from which it derives 50% or more of its revenues.    The RBICS Extended Universe – Industry Group is not currently supported through the RBICS API. 
     * @param {module:model/EntityFocusRequest} entityFocusRequest Request Body to request a list of RBICS Entity Focus objects.
     * @return { Promise.< module:model/EntityFocusResponse > } a Promise, with data of type {@link module:model/EntityFocusResponse }
     */
    getRbicsEntityFocusForList(entityFocusRequest) {
      return this.getRbicsEntityFocusForListWithHttpInfo(entityFocusRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a company's revenue breakdown by RBICS classification.
     * Access a comprehensive, hierarchical breakdown of a company's revenue according to each RBICS industry classification. This endpoint aligns a company's reported business segment revenues with the complete, multi-level RBICS taxonomy, offering the percentage of total revenue attributed to each industry.  For Mutual Funds and ETFs we only have data from L1-L4 and requires additional access to get this data. Note that, the response time can exceed 20+ seconds when querying for more than one year of data.  As such we do not recommend requesting for more than 1 ID at a time for history.   Use the `level` parameter to control the depth of the returned taxonomy, from Economy (L1) down to Sub-Industry (L6). 
     * @param {Array.<String>} ids List of Company identifiers. Accepted identifiers include Ticker-Exchange, Ticker-Regions, CUSIPs, ISINs, SEDOLs, or FactSet Permanent Ids, such as -R, -L, or -E.<p>**ids limit = 2500 per request**</p>    Make note, GET Method URL request lines are also limited to a total length of 8192 bytes (8KB). In cases where the service allows for thousands of ids, which may lead to exceeding this request line limit of 8KB, its advised for any requests with large request lines to be requested through the respective \"POST\" method.</p> 
     * @param {Object} opts Optional parameters
     * @param {Date} opts.startDate Specifies the start date for the requested date range, formatted as **YYYY-MM-DD**. The data returned will be reflective of the classifications or revenue data as of this date and forward. The `startDate` must be equal to or before the `endDate`. Future dates (T+1) are not accepted in this endpoint.  Note:  - If omitted while `endDate` is specified: Data will be fetched from the earliest available record up to the specified end date. - If both `startDate` and `endDate` are omitted: The response will return the latest available data. 
     * @param {Date} opts.endDate Specifies the end date for the requested date range, formatted as **YYYY-MM-DD**. The data returned will be reflective of the classifications or revenue data as of this date and earlier. The `endDate` must be equal to or after the `startDate`. Future dates (T+1) are not accepted in this endpoint.  Note: - If omitted (with `startDate` specified): Data will be returned from the specified start date up to the most recent available date. - If both `startDate` and `endDate` are omitted: The response will return the latest available data. 
     * @param {Number} opts.level Specifies the deepest level of the RBICS taxonomy to be included in the revenue breakdown. The response will include all levels from 1 up to the specified level. For example, a value of '3' will return revenue percentages for Economy (L1), Sector (L2), and Sub-Sector (L3). The default behavior is to return all 6 levels.   |Level|Description|Number of Groups|   |---|---|---|   |1|Economy|14|   |2|Sector|37|   |3|Sub-Sector|109|   |4|Industry Group|366|   |5|Industry|901|   |6|Sub-Industry|1629| 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntityResponse} and HTTP response
     */
    getRbicsEntityRevenueWithHttpInfo(ids, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling getRbicsEntityRevenue");
      }

      let pathParams = {
      };
      let queryParams = {
        'ids': this.apiClient.buildCollectionParam(ids, 'csv'),
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'level': opts['level']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['FactSetApiKey', 'FactSetOAuth2'];
      let contentTypes = [];
      let accepts = ['application/json'];


      let returnType = EntityResponse;

      return this.apiClient.callApi(
        '/factset-rbics/v1/entity/revenue', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a company's revenue breakdown by RBICS classification.
     * Access a comprehensive, hierarchical breakdown of a company's revenue according to each RBICS industry classification. This endpoint aligns a company's reported business segment revenues with the complete, multi-level RBICS taxonomy, offering the percentage of total revenue attributed to each industry.  For Mutual Funds and ETFs we only have data from L1-L4 and requires additional access to get this data. Note that, the response time can exceed 20+ seconds when querying for more than one year of data.  As such we do not recommend requesting for more than 1 ID at a time for history.   Use the `level` parameter to control the depth of the returned taxonomy, from Economy (L1) down to Sub-Industry (L6). 
     * @param {Array.<String>} ids List of Company identifiers. Accepted identifiers include Ticker-Exchange, Ticker-Regions, CUSIPs, ISINs, SEDOLs, or FactSet Permanent Ids, such as -R, -L, or -E.<p>**ids limit = 2500 per request**</p>    Make note, GET Method URL request lines are also limited to a total length of 8192 bytes (8KB). In cases where the service allows for thousands of ids, which may lead to exceeding this request line limit of 8KB, its advised for any requests with large request lines to be requested through the respective \"POST\" method.</p> 
     * @param {Object} opts Optional parameters
     * @param {Date} opts.startDate Specifies the start date for the requested date range, formatted as **YYYY-MM-DD**. The data returned will be reflective of the classifications or revenue data as of this date and forward. The `startDate` must be equal to or before the `endDate`. Future dates (T+1) are not accepted in this endpoint.  Note:  - If omitted while `endDate` is specified: Data will be fetched from the earliest available record up to the specified end date. - If both `startDate` and `endDate` are omitted: The response will return the latest available data. 
     * @param {Date} opts.endDate Specifies the end date for the requested date range, formatted as **YYYY-MM-DD**. The data returned will be reflective of the classifications or revenue data as of this date and earlier. The `endDate` must be equal to or after the `startDate`. Future dates (T+1) are not accepted in this endpoint.  Note: - If omitted (with `startDate` specified): Data will be returned from the specified start date up to the most recent available date. - If both `startDate` and `endDate` are omitted: The response will return the latest available data. 
     * @param {Number} opts.level Specifies the deepest level of the RBICS taxonomy to be included in the revenue breakdown. The response will include all levels from 1 up to the specified level. For example, a value of '3' will return revenue percentages for Economy (L1), Sector (L2), and Sub-Sector (L3). The default behavior is to return all 6 levels.   |Level|Description|Number of Groups|   |---|---|---|   |1|Economy|14|   |2|Sector|37|   |3|Sub-Sector|109|   |4|Industry Group|366|   |5|Industry|901|   |6|Sub-Industry|1629| 
     * @return { Promise.< module:model/EntityResponse > } a Promise, with data of type {@link module:model/EntityResponse }
     */
    getRbicsEntityRevenue(ids, opts) {
      return this.getRbicsEntityRevenueWithHttpInfo(ids, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a company's revenue breakdown by RBICS classification.
     * Access a comprehensive, hierarchical breakdown of a company's revenue according to each RBICS industry classification. This endpoint aligns a company's reported business segment revenues with the complete, multi-level RBICS taxonomy, offering the percentage of total revenue attributed to each industry.  For Mutual Funds and ETFs we only have data from L1-L4 and requires additional access to get this data. Note that, the response time can exceed 20+ seconds when querying for more than one year of data.  As such we do not recommend requesting for more than 1 ID at a time for history.  Use the `level` parameter to control the depth of the returned taxonomy, from Economy (L1) down to Sub-Industry (L6). Use the POST method for large lists of identifiers. 
     * @param {module:model/EntityRequest} entityRequest Request Body to request a list of Entity Revenue objects.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EntityResponse} and HTTP response
     */
    getRbicsEntityRevenueForListWithHttpInfo(entityRequest) {
      let postBody = entityRequest;
      // verify the required parameter 'entityRequest' is set
      if (entityRequest === undefined || entityRequest === null) {
        throw new Error("Missing the required parameter 'entityRequest' when calling getRbicsEntityRevenueForList");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['FactSetApiKey', 'FactSetOAuth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];


      let returnType = EntityResponse;

      return this.apiClient.callApi(
        '/factset-rbics/v1/entity/revenue', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a company's revenue breakdown by RBICS classification.
     * Access a comprehensive, hierarchical breakdown of a company's revenue according to each RBICS industry classification. This endpoint aligns a company's reported business segment revenues with the complete, multi-level RBICS taxonomy, offering the percentage of total revenue attributed to each industry.  For Mutual Funds and ETFs we only have data from L1-L4 and requires additional access to get this data. Note that, the response time can exceed 20+ seconds when querying for more than one year of data.  As such we do not recommend requesting for more than 1 ID at a time for history.  Use the `level` parameter to control the depth of the returned taxonomy, from Economy (L1) down to Sub-Industry (L6). Use the POST method for large lists of identifiers. 
     * @param {module:model/EntityRequest} entityRequest Request Body to request a list of Entity Revenue objects.
     * @return { Promise.< module:model/EntityResponse > } a Promise, with data of type {@link module:model/EntityResponse }
     */
    getRbicsEntityRevenueForList(entityRequest) {
      return this.getRbicsEntityRevenueForListWithHttpInfo(entityRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}





