/*
 * Proposal Generation Engine API
 * Documentation on all available end points in the Proposal Generation API  
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.factset.sdk.ProposalGenerationEngine.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.factset.sdk.ProposalGenerationEngine.models.PortfolioWithRollingStats;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.factset.sdk.ProposalGenerationEngine.JSON;


/**
 * ExPostStatsRollingResponseData
 */
@JsonPropertyOrder({
  ExPostStatsRollingResponseData.JSON_PROPERTY_PORTFOLIO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ExPostStatsRollingResponseData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PORTFOLIO = "portfolio";
  private PortfolioWithRollingStats portfolio;

  public ExPostStatsRollingResponseData() { 
  }

  public ExPostStatsRollingResponseData portfolio(PortfolioWithRollingStats portfolio) {
    this.portfolio = portfolio;
    return this;
  }

   /**
   * Get portfolio
   * @return portfolio
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PORTFOLIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PortfolioWithRollingStats getPortfolio() {
    return portfolio;
  }


  @JsonProperty(JSON_PROPERTY_PORTFOLIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolio(PortfolioWithRollingStats portfolio) {
    this.portfolio = portfolio;
  }


  /**
   * Return true if this ExPostStatsRollingResponse_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExPostStatsRollingResponseData exPostStatsRollingResponseData = (ExPostStatsRollingResponseData) o;
    return Objects.equals(this.portfolio, exPostStatsRollingResponseData.portfolio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExPostStatsRollingResponseData {\n");
    sb.append("    portfolio: ").append(toIndentedString(portfolio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

