/**
 * Real-Time News API
 * Consume FactSet’s StreetAccount news and 3rd party content through an API that seamlessly integrates with [quotes](https://developer.factset.com/api-catalog/real-time-quotes-api), [time series](https://developer.factset.com/api-catalog/real-time-time-series-api), [watchlists](https://developer.factset.com/api-catalog/watchlist-api-digital-portals), and other Functional APIs.  Search for news articles from various news distributors and publishers. Incorporate a multitude of search parameters such as region, category, source, article type and provider-specific meta data, to easily filter out the noise.  All search and list endpoints can be subscribed to receive streamed updates.  News providers include:  * APA * AWP  * Businesswire * Cercle Finance * Direkt News SE * Dow Jones News * dpa * dpa-AFX  * EUWAX * GlobenewsWire * Kauppalehti * MT Newswires * MoneyAM * newsaktuell * OMX * PR Newswire  * Ritzau Finans * StreetAccount News * TDN News        See the [Real-Time Quotes API](https://developer.factset.com/api-catalog/real-time-quotes-api) for access to detailed price and performance information, plus basic support for security identifier cross-reference. 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostNewsArticleListByChainDataArticlesCategoriesItems from './PostNewsArticleListByChainDataArticlesCategoriesItems';
import PostNewsArticleListByChainDataArticlesInstrumentsItems from './PostNewsArticleListByChainDataArticlesInstrumentsItems';
import PostNewsArticleListByChainDataArticlesItemsLanguage from './PostNewsArticleListByChainDataArticlesItemsLanguage';
import PostNewsArticleListByChainDataArticlesTypesItems from './PostNewsArticleListByChainDataArticlesTypesItems';

/**
 * The PostNewsArticleListByChainDataArticlesItems model module.
 * @module model/PostNewsArticleListByChainDataArticlesItems
 */
class PostNewsArticleListByChainDataArticlesItems {
    /**
     * Constructs a new <code>PostNewsArticleListByChainDataArticlesItems</code>.
     * A list of objects. For semantical context see the description of the parent array.
     * @alias module:model/PostNewsArticleListByChainDataArticlesItems
     */
    constructor() { 
        
        PostNewsArticleListByChainDataArticlesItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostNewsArticleListByChainDataArticlesItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostNewsArticleListByChainDataArticlesItems} obj Optional instance to populate.
     * @return {module:model/PostNewsArticleListByChainDataArticlesItems} The populated <code>PostNewsArticleListByChainDataArticlesItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostNewsArticleListByChainDataArticlesItems();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], [PostNewsArticleListByChainDataArticlesTypesItems]);
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = PostNewsArticleListByChainDataArticlesItemsLanguage.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [PostNewsArticleListByChainDataArticlesCategoriesItems]);
            }
            if (data.hasOwnProperty('instruments')) {
                obj['instruments'] = ApiClient.convertToType(data['instruments'], [PostNewsArticleListByChainDataArticlesInstrumentsItems]);
            }
        }
        return obj;
    }


}

/**
 * Identifier of the news article.
 * @member {String} code
 */
PostNewsArticleListByChainDataArticlesItems.prototype['code'] = undefined;

/**
 * Date and time of the news article.
 * @member {Date} time
 */
PostNewsArticleListByChainDataArticlesItems.prototype['time'] = undefined;

/**
 * Headline of the news article represented as text with HTML entity encoding but without HTML tags.
 * @member {String} headline
 */
PostNewsArticleListByChainDataArticlesItems.prototype['headline'] = undefined;

/**
 * Textual summary of the body of the news article or `null` if no summary was provided by the news article distributor.
 * @member {String} summary
 */
PostNewsArticleListByChainDataArticlesItems.prototype['summary'] = undefined;

/**
 * Types of news article. See endpoint `/news/article/type/list` for possible values.
 * @member {Array.<module:model/PostNewsArticleListByChainDataArticlesTypesItems>} types
 */
PostNewsArticleListByChainDataArticlesItems.prototype['types'] = undefined;

/**
 * @member {module:model/PostNewsArticleListByChainDataArticlesItemsLanguage} language
 */
PostNewsArticleListByChainDataArticlesItems.prototype['language'] = undefined;

/**
 * Categories related to the news article. See endpoint `/category/list` for possible values.
 * @member {Array.<module:model/PostNewsArticleListByChainDataArticlesCategoriesItems>} categories
 */
PostNewsArticleListByChainDataArticlesItems.prototype['categories'] = undefined;

/**
 * Set of stock instruments related to the article. The set is not updated in the course of corporate actions, e.g. when the related company obtains a new instrument after a spin-off.
 * @member {Array.<module:model/PostNewsArticleListByChainDataArticlesInstrumentsItems>} instruments
 */
PostNewsArticleListByChainDataArticlesItems.prototype['instruments'] = undefined;






export default PostNewsArticleListByChainDataArticlesItems;

