/**
 * FactSet RBICS
 * FactSet Revere Business Industry Classification System (RBICS) is a comprehensive structured taxonomy to classify companies by what they primarily do. It delivers a granular view for investors by classifying companies using a bottom-up approach according to the products and services they provide. By combining this approach with a top-level grouping based on companies' behavior similarities and stock co-movement, FactSet RBICS delivers unprecedented precision for 1,400+ sector groups.  RBICS Focus is a six level classification which highlights the companys main business. It is based on the company business line/s that stand for majority of a the revenue that the company generates. Updated monthly. For more details, visit [Online Assistant Page #20710](https://oa.apps.factset.com/pages/20710).<p><b>Rate limit is set to 10 requests per second</b>.</p> 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntityFocus model module.
 * @module model/EntityFocus
 */
class EntityFocus {
    /**
     * Constructs a new <code>EntityFocus</code>.
     * @alias module:model/EntityFocus
     * @extends Object
     * @param requestId {String} Company identifier used in request.
     * @param fsymId {String} FactSet Company identifier being classified.
     * @param firstDate {Date} First date of the classification.
     * @param lastDate {Date} Date when the classification became no longer valid.
     */
    constructor(requestId, fsymId, firstDate, lastDate) { 
        
        EntityFocus.initialize(this, requestId, fsymId, firstDate, lastDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestId, fsymId, firstDate, lastDate) { 
        obj['requestId'] = requestId;
        obj['fsymId'] = fsymId;
        obj['firstDate'] = firstDate;
        obj['lastDate'] = lastDate;
    }

    /**
     * Constructs a <code>EntityFocus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityFocus} obj Optional instance to populate.
     * @return {module:model/EntityFocus} The populated <code>EntityFocus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityFocus();

            if (data.hasOwnProperty('requestId') && obj['requestId'] === undefined) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('fsymId') && obj['fsymId'] === undefined) {
                obj['fsymId'] = ApiClient.convertToType(data['fsymId'], 'String');
            }
            if (data.hasOwnProperty('firstDate') && obj['firstDate'] === undefined) {
                obj['firstDate'] = ApiClient.convertToType(data['firstDate'], 'Date');
            }
            if (data.hasOwnProperty('lastDate') && obj['lastDate'] === undefined) {
                obj['lastDate'] = ApiClient.convertToType(data['lastDate'], 'Date');
            }
            
            ApiClient.constructFromObject(data, obj, Object);
            
        }
        return obj;
    }


}

/**
 * Company identifier used in request.
 * @member {String} requestId
 */
EntityFocus.prototype['requestId'] = undefined;

/**
 * FactSet Company identifier being classified.
 * @member {String} fsymId
 */
EntityFocus.prototype['fsymId'] = undefined;

/**
 * First date of the classification.
 * @member {Date} firstDate
 */
EntityFocus.prototype['firstDate'] = undefined;

/**
 * Date when the classification became no longer valid.
 * @member {Date} lastDate
 */
EntityFocus.prototype['lastDate'] = undefined;






export default EntityFocus;

