# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from fds.sdk.PriceAlertingAPIforDigitalPortals.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from fds.sdk.PriceAlertingAPIforDigitalPortals.model.alerting_prices_basic_trigger_list_data import AlertingPricesBasicTriggerListData
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.alerting_prices_basic_trigger_list_data_filter import AlertingPricesBasicTriggerListDataFilter
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.alerting_prices_basic_trigger_list_data_filter_status import AlertingPricesBasicTriggerListDataFilterStatus
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.alerting_prices_basic_trigger_list_meta import AlertingPricesBasicTriggerListMeta
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.alerting_prices_basic_trigger_list_meta_pagination import AlertingPricesBasicTriggerListMetaPagination
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.attributes_member import AttributesMember
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.cursor_based_pagination_output_object import CursorBasedPaginationOutputObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.cursor_based_pagination_output_object_without_total import CursorBasedPaginationOutputObjectWithoutTotal
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.error_meta_object import ErrorMetaObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.error_object import ErrorObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_object import InlineObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200 import InlineResponse200
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001 import InlineResponse2001
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001_data import InlineResponse2001Data
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001_meta import InlineResponse2001Meta
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001_trigger import InlineResponse2001Trigger
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001_trigger_price import InlineResponse2001TriggerPrice
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2001_trigger_status import InlineResponse2001TriggerStatus
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2002 import InlineResponse2002
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2002_data import InlineResponse2002Data
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2003 import InlineResponse2003
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2003_data import InlineResponse2003Data
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response2003_range import InlineResponse2003Range
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data import InlineResponse200Data
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_price import InlineResponse200DataPrice
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_trigger import InlineResponse200DataTrigger
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_trigger_notation import InlineResponse200DataTriggerNotation
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_trigger_price import InlineResponse200DataTriggerPrice
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_trigger_range import InlineResponse200DataTriggerRange
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_data_trigger_status import InlineResponse200DataTriggerStatus
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.inline_response200_meta import InlineResponse200Meta
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.language_member import LanguageMember
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.offset_based_pagination_output_object import OffsetBasedPaginationOutputObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.offset_based_pagination_output_object_without_total import OffsetBasedPaginationOutputObjectWithoutTotal
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.partial_output_object import PartialOutputObject
from fds.sdk.PriceAlertingAPIforDigitalPortals.model.status_object import StatusObject
