"""
    Best Execution Analytics for Smarter Trading (BEAST) API

    Enables clients to programmatically access the underlying data which powers the BEAST Liquidity Analytics (LA) and Transaction Cost Analysis (TCA) applications.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: api@factset.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401
from multiprocessing.pool import ApplyResult
import typing

from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.api_client import ApiClient, Endpoint as _Endpoint
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.exceptions import ApiException
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model.error_response import ErrorResponse
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model.liquidity_analytics_response_root import LiquidityAnalyticsResponseRoot
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model.quotes_analytics_response_root import QuotesAnalyticsResponseRoot
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model.trades_analytics_response_root import TradesAnalyticsResponseRoot
from fds.sdk.BestExecutionAnalyticsforSmarterTradingBEAST.model.volume_analytics_response_root_v3 import VolumeAnalyticsResponseRootV3





class LiquidityAnalyticsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        self.get_liquidity_analytics_endpoint = _Endpoint(
            settings={
                'response_type': (
                  { 200: (LiquidityAnalyticsResponseRoot,), 400: (ErrorResponse,),  },
                  None
                ),
                'auth': [
                    'FactSetApiKey',
                    'FactSetOAuth2'
                ],
                'endpoint_path': '/tca/liquidity/liquidity-analytics',
                'operation_id': 'get_liquidity_analytics',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'required': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'security_ids':
                        ([str],),
                    'start_date':
                        (date,),
                    'end_date':
                        (date,),
                },
                'attribute_map': {
                    'security_ids': 'securityIds',
                    'start_date': 'startDate',
                    'end_date': 'endDate',
                },
                'location_map': {
                    'security_ids': 'query',
                    'start_date': 'query',
                    'end_date': 'query',
                },
                'collection_format_map': {
                    'security_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

        self.get_liquidity_quotes_endpoint = _Endpoint(
            settings={
                'response_type': (
                  { 200: (QuotesAnalyticsResponseRoot,), 400: (ErrorResponse,),  },
                  None
                ),
                'auth': [
                    'FactSetApiKey',
                    'FactSetOAuth2'
                ],
                'endpoint_path': '/tca/liquidity/quotes',
                'operation_id': 'get_liquidity_quotes',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'required': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'security_ids':
                        ([str],),
                    'start_date':
                        (date,),
                    'end_date':
                        (date,),
                },
                'attribute_map': {
                    'security_ids': 'securityIds',
                    'start_date': 'startDate',
                    'end_date': 'endDate',
                },
                'location_map': {
                    'security_ids': 'query',
                    'start_date': 'query',
                    'end_date': 'query',
                },
                'collection_format_map': {
                    'security_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

        self.get_liquidity_trades_endpoint = _Endpoint(
            settings={
                'response_type': (
                  { 200: (TradesAnalyticsResponseRoot,), 400: (ErrorResponse,),  },
                  None
                ),
                'auth': [
                    'FactSetApiKey',
                    'FactSetOAuth2'
                ],
                'endpoint_path': '/tca/liquidity/trades',
                'operation_id': 'get_liquidity_trades',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'required': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'security_ids':
                        ([str],),
                    'start_date':
                        (date,),
                    'end_date':
                        (date,),
                },
                'attribute_map': {
                    'security_ids': 'securityIds',
                    'start_date': 'startDate',
                    'end_date': 'endDate',
                },
                'location_map': {
                    'security_ids': 'query',
                    'start_date': 'query',
                    'end_date': 'query',
                },
                'collection_format_map': {
                    'security_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

        self.get_liquidity_volume_analytics_endpoint = _Endpoint(
            settings={
                'response_type': (
                  { 200: (VolumeAnalyticsResponseRootV3,), 400: (ErrorResponse,),  },
                  None
                ),
                'auth': [
                    'FactSetApiKey',
                    'FactSetOAuth2'
                ],
                'endpoint_path': '/tca/liquidity/volume-analytics',
                'operation_id': 'get_liquidity_volume_analytics',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'required': [
                    'security_ids',
                    'start_date',
                    'end_date',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'security_ids':
                        ([str],),
                    'start_date':
                        (date,),
                    'end_date':
                        (date,),
                },
                'attribute_map': {
                    'security_ids': 'securityIds',
                    'start_date': 'startDate',
                    'end_date': 'endDate',
                },
                'location_map': {
                    'security_ids': 'query',
                    'start_date': 'query',
                    'end_date': 'query',
                },
                'collection_format_map': {
                    'security_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )


    @staticmethod
    def apply_kwargs_defaults(kwargs, return_http_data_only, async_req):
        kwargs["async_req"] = async_req
        kwargs["_return_http_data_only"] = return_http_data_only
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_spec_property_naming"] = kwargs.get("_spec_property_naming", False)
        kwargs["_content_type"] = kwargs.get("_content_type")
        kwargs["_host_index"] = kwargs.get("_host_index")


    def get_liquidity_analytics(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> LiquidityAnalyticsResponseRoot:
        """Get Liquidity Analytics  # noqa: E501

        Get Liquidity Analytics  # noqa: E501
        This method makes a synchronous HTTP request. Returns the http data only

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            LiquidityAnalyticsResponseRoot
                Response Object
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_analytics_with_http_info(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> typing.Tuple[LiquidityAnalyticsResponseRoot, int, typing.MutableMapping]:
        """Get Liquidity Analytics  # noqa: E501

        Get Liquidity Analytics  # noqa: E501
        This method makes a synchronous HTTP request. Returns http data, http status and headers

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            LiquidityAnalyticsResponseRoot
                Response Object
            int
                Http Status Code
            dict
                Dictionary of the response headers
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_analytics_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[LiquidityAnalyticsResponseRoot]":
        """Get Liquidity Analytics  # noqa: E501

        Get Liquidity Analytics  # noqa: E501
        This method makes a asynchronous HTTP request. Returns the http data, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[LiquidityAnalyticsResponseRoot]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_analytics_with_http_info_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[typing.Tuple[LiquidityAnalyticsResponseRoot, int, typing.MutableMapping]]":
        """Get Liquidity Analytics  # noqa: E501

        Get Liquidity Analytics  # noqa: E501
        This method makes a asynchronous HTTP request. Returns http data, http status and headers, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[(LiquidityAnalyticsResponseRoot, int, typing.Dict)]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_analytics_endpoint.call_with_http_info(**kwargs)


    def get_liquidity_quotes(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> QuotesAnalyticsResponseRoot:
        """Get Liquidity Quotes  # noqa: E501

        Get Liquidity Quotes  # noqa: E501
        This method makes a synchronous HTTP request. Returns the http data only

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            QuotesAnalyticsResponseRoot
                Response Object
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_quotes_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_quotes_with_http_info(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> typing.Tuple[QuotesAnalyticsResponseRoot, int, typing.MutableMapping]:
        """Get Liquidity Quotes  # noqa: E501

        Get Liquidity Quotes  # noqa: E501
        This method makes a synchronous HTTP request. Returns http data, http status and headers

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            QuotesAnalyticsResponseRoot
                Response Object
            int
                Http Status Code
            dict
                Dictionary of the response headers
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_quotes_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_quotes_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[QuotesAnalyticsResponseRoot]":
        """Get Liquidity Quotes  # noqa: E501

        Get Liquidity Quotes  # noqa: E501
        This method makes a asynchronous HTTP request. Returns the http data, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[QuotesAnalyticsResponseRoot]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_quotes_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_quotes_with_http_info_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[typing.Tuple[QuotesAnalyticsResponseRoot, int, typing.MutableMapping]]":
        """Get Liquidity Quotes  # noqa: E501

        Get Liquidity Quotes  # noqa: E501
        This method makes a asynchronous HTTP request. Returns http data, http status and headers, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[(QuotesAnalyticsResponseRoot, int, typing.Dict)]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_quotes_endpoint.call_with_http_info(**kwargs)


    def get_liquidity_trades(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> TradesAnalyticsResponseRoot:
        """Get Liquidity Trades  # noqa: E501

        Get Liquidity Trades  # noqa: E501
        This method makes a synchronous HTTP request. Returns the http data only

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            TradesAnalyticsResponseRoot
                Response Object
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_trades_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_trades_with_http_info(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> typing.Tuple[TradesAnalyticsResponseRoot, int, typing.MutableMapping]:
        """Get Liquidity Trades  # noqa: E501

        Get Liquidity Trades  # noqa: E501
        This method makes a synchronous HTTP request. Returns http data, http status and headers

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            TradesAnalyticsResponseRoot
                Response Object
            int
                Http Status Code
            dict
                Dictionary of the response headers
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_trades_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_trades_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[TradesAnalyticsResponseRoot]":
        """Get Liquidity Trades  # noqa: E501

        Get Liquidity Trades  # noqa: E501
        This method makes a asynchronous HTTP request. Returns the http data, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[TradesAnalyticsResponseRoot]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_trades_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_trades_with_http_info_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[typing.Tuple[TradesAnalyticsResponseRoot, int, typing.MutableMapping]]":
        """Get Liquidity Trades  # noqa: E501

        Get Liquidity Trades  # noqa: E501
        This method makes a asynchronous HTTP request. Returns http data, http status and headers, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[(TradesAnalyticsResponseRoot, int, typing.Dict)]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_trades_endpoint.call_with_http_info(**kwargs)


    def get_liquidity_volume_analytics(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> VolumeAnalyticsResponseRootV3:
        """Get Liquidity Volume Analytics  # noqa: E501

        Get Liquidity Volume Analytics  # noqa: E501
        This method makes a synchronous HTTP request. Returns the http data only

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            VolumeAnalyticsResponseRootV3
                Response Object
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_volume_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_volume_analytics_with_http_info(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> typing.Tuple[VolumeAnalyticsResponseRootV3, int, typing.MutableMapping]:
        """Get Liquidity Volume Analytics  # noqa: E501

        Get Liquidity Volume Analytics  # noqa: E501
        This method makes a synchronous HTTP request. Returns http data, http status and headers

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            VolumeAnalyticsResponseRootV3
                Response Object
            int
                Http Status Code
            dict
                Dictionary of the response headers
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=False)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_volume_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_volume_analytics_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[VolumeAnalyticsResponseRootV3]":
        """Get Liquidity Volume Analytics  # noqa: E501

        Get Liquidity Volume Analytics  # noqa: E501
        This method makes a asynchronous HTTP request. Returns the http data, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[VolumeAnalyticsResponseRootV3]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=True, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_volume_analytics_endpoint.call_with_http_info(**kwargs)

    def get_liquidity_volume_analytics_with_http_info_async(
        self,
        security_ids,
        start_date,
        end_date,
        **kwargs
    ) -> "ApplyResult[typing.Tuple[VolumeAnalyticsResponseRootV3, int, typing.MutableMapping]]":
        """Get Liquidity Volume Analytics  # noqa: E501

        Get Liquidity Volume Analytics  # noqa: E501
        This method makes a asynchronous HTTP request. Returns http data, http status and headers, wrapped in ApplyResult

        Args:
            security_ids ([str]): ISIN for European securities, otherwise TICKER
            start_date (date): Date in the format YYYY-MM-DD
            end_date (date): Date in the format YYYY-MM-DD

        Keyword Args:
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True. NOTE: if this API returns a file, it is the responsibility
                of the caller to close the file stream.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
        Returns:
            ApplyResult[(VolumeAnalyticsResponseRootV3, int, typing.Dict)]
        """
        self.apply_kwargs_defaults(kwargs=kwargs, return_http_data_only=False, async_req=True)
        kwargs['security_ids'] = \
            security_ids
        kwargs['start_date'] = \
            start_date
        kwargs['end_date'] = \
            end_date
        return self.get_liquidity_volume_analytics_endpoint.call_with_http_info(**kwargs)


