/*
 * FactSet Funds and ETF API
 * FactSet Mutual Funds and ETFs Reference provides fund-specific reference information as well as FactSet's proprietary classification system. It includes but is not limited to the following coverage    * Fund descriptions    * A seven-tier classification system   * Leverage information   * Fees and expenses    * Portfolio managers       FactSet Mutual Funds Time Series provides quantitative data items on a historical basis. It includes but is not limited to the following coverage    * Net asset value   * Fund flows    * Assets under management   * Total return      In addition to core reference and time series data, the API enables broader fund analytics and workflows, including:   * Fund summary and classification insights such as domicile, structure, segments, and similar funds    * Performance analytics including historical returns, snapshot returns across time horizons, and yield data   * Cost, fee, and risk metrics including expense ratios, regulatory/tax exposure, and risk measures   * Portfolio exposure and analytics including asset allocation, sector weightage, geographic exposure, and top holdings    * Trading and liquidity characteristics for evaluating tradability    * ETF-specific scoring and ratings to assess efficiency, tradability, and fit relative to benchmarks    * Distribution and income data for understanding payouts and investor returns   <p>This API is rate-limited to 10 requests per second and 10 concurrent requests per user. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.factset.sdk.FactSetFunds.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.factset.sdk.FactSetFunds.models.FundsErrorObject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.factset.sdk.FactSetFunds.JSON;


/**
 * YieldsAllOf
 */
@JsonPropertyOrder({
  YieldsAllOf.JSON_PROPERTY_ERROR,
  YieldsAllOf.JSON_PROPERTY_SEC30_DAY_YIELD_NET,
  YieldsAllOf.JSON_PROPERTY_SEC30_DAY_YIELD_GROSS,
  YieldsAllOf.JSON_PROPERTY_SEC7_DAY_YIELD_NET,
  YieldsAllOf.JSON_PROPERTY_SEC7_DAY_YIELD_GROSS,
  YieldsAllOf.JSON_PROPERTY_COUPON_RATE,
  YieldsAllOf.JSON_PROPERTY_YIELD_TO_MATURITY,
  YieldsAllOf.JSON_PROPERTY_YIELD_TO_WORST,
  YieldsAllOf.JSON_PROPERTY_REAL_YIELD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class YieldsAllOf implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ERROR = "error";
  private JsonNullable<FundsErrorObject> error = JsonNullable.<FundsErrorObject>undefined();

  public static final String JSON_PROPERTY_SEC30_DAY_YIELD_NET = "sec30DayYieldNet";
  private JsonNullable<Double> sec30DayYieldNet = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_SEC30_DAY_YIELD_GROSS = "sec30DayYieldGross";
  private JsonNullable<Double> sec30DayYieldGross = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_SEC7_DAY_YIELD_NET = "sec7DayYieldNet";
  private JsonNullable<Double> sec7DayYieldNet = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_SEC7_DAY_YIELD_GROSS = "sec7DayYieldGross";
  private JsonNullable<Double> sec7DayYieldGross = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_COUPON_RATE = "couponRate";
  private JsonNullable<Double> couponRate = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_YIELD_TO_MATURITY = "yieldToMaturity";
  private JsonNullable<Double> yieldToMaturity = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_YIELD_TO_WORST = "yieldToWorst";
  private JsonNullable<Double> yieldToWorst = JsonNullable.<Double>undefined();

  public static final String JSON_PROPERTY_REAL_YIELD = "realYield";
  private JsonNullable<Double> realYield = JsonNullable.<Double>undefined();

  public YieldsAllOf() { 
  }

  public YieldsAllOf error(FundsErrorObject error) {
    this.error = JsonNullable.<FundsErrorObject>of(error);
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public FundsErrorObject getError() {
        return error.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<FundsErrorObject> getError_JsonNullable() {
    return error;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR)
  public void setError_JsonNullable(JsonNullable<FundsErrorObject> error) {
    this.error = error;
  }

  public void setError(FundsErrorObject error) {
    this.error = JsonNullable.<FundsErrorObject>of(error);
  }


  public YieldsAllOf sec30DayYieldNet(Double sec30DayYieldNet) {
    this.sec30DayYieldNet = JsonNullable.<Double>of(sec30DayYieldNet);
    return this;
  }

   /**
   * 30 Days Net SEC yield is the subsidized or after waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only
   * @return sec30DayYieldNet
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "4.15", value = "30 Days Net SEC yield is the subsidized or after waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only")
  @JsonIgnore

  public Double getSec30DayYieldNet() {
        return sec30DayYieldNet.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SEC30_DAY_YIELD_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getSec30DayYieldNet_JsonNullable() {
    return sec30DayYieldNet;
  }
  
  @JsonProperty(JSON_PROPERTY_SEC30_DAY_YIELD_NET)
  public void setSec30DayYieldNet_JsonNullable(JsonNullable<Double> sec30DayYieldNet) {
    this.sec30DayYieldNet = sec30DayYieldNet;
  }

  public void setSec30DayYieldNet(Double sec30DayYieldNet) {
    this.sec30DayYieldNet = JsonNullable.<Double>of(sec30DayYieldNet);
  }


  public YieldsAllOf sec30DayYieldGross(Double sec30DayYieldGross) {
    this.sec30DayYieldGross = JsonNullable.<Double>of(sec30DayYieldGross);
    return this;
  }

   /**
   * 30 Gross SEC yield is the unsubsidized or before waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only
   * @return sec30DayYieldGross
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "1.16", value = "30 Gross SEC yield is the unsubsidized or before waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only")
  @JsonIgnore

  public Double getSec30DayYieldGross() {
        return sec30DayYieldGross.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SEC30_DAY_YIELD_GROSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getSec30DayYieldGross_JsonNullable() {
    return sec30DayYieldGross;
  }
  
  @JsonProperty(JSON_PROPERTY_SEC30_DAY_YIELD_GROSS)
  public void setSec30DayYieldGross_JsonNullable(JsonNullable<Double> sec30DayYieldGross) {
    this.sec30DayYieldGross = sec30DayYieldGross;
  }

  public void setSec30DayYieldGross(Double sec30DayYieldGross) {
    this.sec30DayYieldGross = JsonNullable.<Double>of(sec30DayYieldGross);
  }


  public YieldsAllOf sec7DayYieldNet(Double sec7DayYieldNet) {
    this.sec7DayYieldNet = JsonNullable.<Double>of(sec7DayYieldNet);
    return this;
  }

   /**
   * 7 Days Net SEC yield is the subsidized or after waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only
   * @return sec7DayYieldNet
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "4.15", value = "7 Days Net SEC yield is the subsidized or after waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only")
  @JsonIgnore

  public Double getSec7DayYieldNet() {
        return sec7DayYieldNet.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SEC7_DAY_YIELD_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getSec7DayYieldNet_JsonNullable() {
    return sec7DayYieldNet;
  }
  
  @JsonProperty(JSON_PROPERTY_SEC7_DAY_YIELD_NET)
  public void setSec7DayYieldNet_JsonNullable(JsonNullable<Double> sec7DayYieldNet) {
    this.sec7DayYieldNet = sec7DayYieldNet;
  }

  public void setSec7DayYieldNet(Double sec7DayYieldNet) {
    this.sec7DayYieldNet = JsonNullable.<Double>of(sec7DayYieldNet);
  }


  public YieldsAllOf sec7DayYieldGross(Double sec7DayYieldGross) {
    this.sec7DayYieldGross = JsonNullable.<Double>of(sec7DayYieldGross);
    return this;
  }

   /**
   * 7 Gross SEC yield is the unsubsidized or before waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only.
   * @return sec7DayYieldGross
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "1.16", value = "7 Gross SEC yield is the unsubsidized or before waivers. The Net will be bigger than the Gross if part of the fees are waived. If Gross and Net are equal, no fees were waived. SEC Yield for Mutual Funds is in percentage form while ETFs will depend on the fund. Available for US Funds Only.")
  @JsonIgnore

  public Double getSec7DayYieldGross() {
        return sec7DayYieldGross.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SEC7_DAY_YIELD_GROSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getSec7DayYieldGross_JsonNullable() {
    return sec7DayYieldGross;
  }
  
  @JsonProperty(JSON_PROPERTY_SEC7_DAY_YIELD_GROSS)
  public void setSec7DayYieldGross_JsonNullable(JsonNullable<Double> sec7DayYieldGross) {
    this.sec7DayYieldGross = sec7DayYieldGross;
  }

  public void setSec7DayYieldGross(Double sec7DayYieldGross) {
    this.sec7DayYieldGross = JsonNullable.<Double>of(sec7DayYieldGross);
  }


  public YieldsAllOf couponRate(Double couponRate) {
    this.couponRate = JsonNullable.<Double>of(couponRate);
    return this;
  }

   /**
   * Coupon Rate for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.
   * @return couponRate
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "3.75", value = "Coupon Rate for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.")
  @JsonIgnore

  public Double getCouponRate() {
        return couponRate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COUPON_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getCouponRate_JsonNullable() {
    return couponRate;
  }
  
  @JsonProperty(JSON_PROPERTY_COUPON_RATE)
  public void setCouponRate_JsonNullable(JsonNullable<Double> couponRate) {
    this.couponRate = couponRate;
  }

  public void setCouponRate(Double couponRate) {
    this.couponRate = JsonNullable.<Double>of(couponRate);
  }


  public YieldsAllOf yieldToMaturity(Double yieldToMaturity) {
    this.yieldToMaturity = JsonNullable.<Double>of(yieldToMaturity);
    return this;
  }

   /**
   * Yield to Maturity for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.
   * @return yieldToMaturity
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "4.32", value = "Yield to Maturity for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.")
  @JsonIgnore

  public Double getYieldToMaturity() {
        return yieldToMaturity.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_YIELD_TO_MATURITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getYieldToMaturity_JsonNullable() {
    return yieldToMaturity;
  }
  
  @JsonProperty(JSON_PROPERTY_YIELD_TO_MATURITY)
  public void setYieldToMaturity_JsonNullable(JsonNullable<Double> yieldToMaturity) {
    this.yieldToMaturity = yieldToMaturity;
  }

  public void setYieldToMaturity(Double yieldToMaturity) {
    this.yieldToMaturity = JsonNullable.<Double>of(yieldToMaturity);
  }


  public YieldsAllOf yieldToWorst(Double yieldToWorst) {
    this.yieldToWorst = JsonNullable.<Double>of(yieldToWorst);
    return this;
  }

   /**
   * Yield to Worst for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.
   * @return yieldToWorst
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "4.3", value = "Yield to Worst for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.")
  @JsonIgnore

  public Double getYieldToWorst() {
        return yieldToWorst.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_YIELD_TO_WORST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getYieldToWorst_JsonNullable() {
    return yieldToWorst;
  }
  
  @JsonProperty(JSON_PROPERTY_YIELD_TO_WORST)
  public void setYieldToWorst_JsonNullable(JsonNullable<Double> yieldToWorst) {
    this.yieldToWorst = yieldToWorst;
  }

  public void setYieldToWorst(Double yieldToWorst) {
    this.yieldToWorst = JsonNullable.<Double>of(yieldToWorst);
  }


  public YieldsAllOf realYield(Double realYield) {
    this.realYield = JsonNullable.<Double>of(realYield);
    return this;
  }

   /**
   * Real Yield for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.
   * @return realYield
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "4.31", value = "Real Yield for a given fund. This data item is available only with the Analytics product package. If the product is not enabled, the field will be omitted from the response.")
  @JsonIgnore

  public Double getRealYield() {
        return realYield.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REAL_YIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Double> getRealYield_JsonNullable() {
    return realYield;
  }
  
  @JsonProperty(JSON_PROPERTY_REAL_YIELD)
  public void setRealYield_JsonNullable(JsonNullable<Double> realYield) {
    this.realYield = realYield;
  }

  public void setRealYield(Double realYield) {
    this.realYield = JsonNullable.<Double>of(realYield);
  }


  /**
   * Return true if this Yields_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YieldsAllOf yieldsAllOf = (YieldsAllOf) o;
    return equalsNullable(this.error, yieldsAllOf.error) &&
        equalsNullable(this.sec30DayYieldNet, yieldsAllOf.sec30DayYieldNet) &&
        equalsNullable(this.sec30DayYieldGross, yieldsAllOf.sec30DayYieldGross) &&
        equalsNullable(this.sec7DayYieldNet, yieldsAllOf.sec7DayYieldNet) &&
        equalsNullable(this.sec7DayYieldGross, yieldsAllOf.sec7DayYieldGross) &&
        equalsNullable(this.couponRate, yieldsAllOf.couponRate) &&
        equalsNullable(this.yieldToMaturity, yieldsAllOf.yieldToMaturity) &&
        equalsNullable(this.yieldToWorst, yieldsAllOf.yieldToWorst) &&
        equalsNullable(this.realYield, yieldsAllOf.realYield);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(error), hashCodeNullable(sec30DayYieldNet), hashCodeNullable(sec30DayYieldGross), hashCodeNullable(sec7DayYieldNet), hashCodeNullable(sec7DayYieldGross), hashCodeNullable(couponRate), hashCodeNullable(yieldToMaturity), hashCodeNullable(yieldToWorst), hashCodeNullable(realYield));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YieldsAllOf {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    sec30DayYieldNet: ").append(toIndentedString(sec30DayYieldNet)).append("\n");
    sb.append("    sec30DayYieldGross: ").append(toIndentedString(sec30DayYieldGross)).append("\n");
    sb.append("    sec7DayYieldNet: ").append(toIndentedString(sec7DayYieldNet)).append("\n");
    sb.append("    sec7DayYieldGross: ").append(toIndentedString(sec7DayYieldGross)).append("\n");
    sb.append("    couponRate: ").append(toIndentedString(couponRate)).append("\n");
    sb.append("    yieldToMaturity: ").append(toIndentedString(yieldToMaturity)).append("\n");
    sb.append("    yieldToWorst: ").append(toIndentedString(yieldToWorst)).append("\n");
    sb.append("    realYield: ").append(toIndentedString(realYield)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

