/*
 * Private Equity & Venture Capital API
 * Comprehensive API for accessing private equity and venture capital data including funds, general partners, transactions, and portfolio companies. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.factset.sdk.FactSetPrivateEquityandVentureCapital.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.factset.sdk.FactSetPrivateEquityandVentureCapital.JSON;


/**
 * FundCashflowsRequestData
 */
@JsonPropertyOrder({
  FundCashflowsRequestData.JSON_PROPERTY_IDS,
  FundCashflowsRequestData.JSON_PROPERTY_START_DATE,
  FundCashflowsRequestData.JSON_PROPERTY_END_DATE,
  FundCashflowsRequestData.JSON_PROPERTY_CF_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class FundCashflowsRequestData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_IDS = "ids";
  private java.util.List<String> ids = new java.util.ArrayList<>();

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private LocalDate startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private LocalDate endDate;

  /**
   * Cash flow type filter
   */
  public enum CfTypeEnum {
    CONTRIBUTION("CONTRIBUTION"),
    
    DISTRIBUTION("DISTRIBUTION"),
    
    NAV("NAV");

    private String value;

    CfTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CfTypeEnum fromValue(String value) {
      for (CfTypeEnum b : CfTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CF_TYPE = "cfType";
  private CfTypeEnum cfType;

  public FundCashflowsRequestData() { 
  }

  @JsonCreator
  public FundCashflowsRequestData(
    @JsonProperty(value=JSON_PROPERTY_IDS, required=true) java.util.List<String> ids
  ) {
    this();
    this.ids = ids;
  }

  public FundCashflowsRequestData ids(java.util.List<String> ids) {
    this.ids = ids;
    return this;
  }

  public FundCashflowsRequestData addIdsItem(String idsItem) {
    this.ids.add(idsItem);
    return this;
  }

   /**
   * List of fund entity identifiers, which can be retrieved from the /universe endpoint
   * @return ids
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of fund entity identifiers, which can be retrieved from the /universe endpoint")
  @JsonProperty(JSON_PROPERTY_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public java.util.List<String> getIds() {
    return ids;
  }


  @JsonProperty(JSON_PROPERTY_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIds(java.util.List<String> ids) {
    this.ids = ids;
  }


  public FundCashflowsRequestData startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Specifies the start date for the requested date range, formatted as YYYY-MM-DD. Future dates (T+1) are not accepted in this endpoint.
   * @return startDate
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Specifies the start date for the requested date range, formatted as YYYY-MM-DD. Future dates (T+1) are not accepted in this endpoint.")
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }


  public FundCashflowsRequestData endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Specifies the end date for the requested date range, formatted as YYYY-MM-DD. Future dates (T+1) are not accepted in this endpoint.
   * @return endDate
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Specifies the end date for the requested date range, formatted as YYYY-MM-DD. Future dates (T+1) are not accepted in this endpoint.")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }


  public FundCashflowsRequestData cfType(CfTypeEnum cfType) {
    this.cfType = cfType;
    return this;
  }

   /**
   * Cash flow type filter
   * @return cfType
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "Cash flow type filter")
  @JsonProperty(JSON_PROPERTY_CF_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CfTypeEnum getCfType() {
    return cfType;
  }


  @JsonProperty(JSON_PROPERTY_CF_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCfType(CfTypeEnum cfType) {
    this.cfType = cfType;
  }


  /**
   * Return true if this FundCashflowsRequest_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundCashflowsRequestData fundCashflowsRequestData = (FundCashflowsRequestData) o;
    return Objects.equals(this.ids, fundCashflowsRequestData.ids) &&
        Objects.equals(this.startDate, fundCashflowsRequestData.startDate) &&
        Objects.equals(this.endDate, fundCashflowsRequestData.endDate) &&
        Objects.equals(this.cfType, fundCashflowsRequestData.cfType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ids, startDate, endDate, cfType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundCashflowsRequestData {\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    cfType: ").append(toIndentedString(cfType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

