/**
 * PA Engine API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: 3.15.6
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PAComponent from './PAComponent';

/**
 * The PAComponentRoot model module.
 * @module model/PAComponentRoot
 */
class PAComponentRoot {
    /**
     * Constructs a new <code>PAComponentRoot</code>.
     * @alias module:model/PAComponentRoot
     * @param data {module:model/PAComponent} 
     */
    constructor(data) { 
        
        PAComponentRoot.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>PAComponentRoot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PAComponentRoot} obj Optional instance to populate.
     * @return {module:model/PAComponentRoot} The populated <code>PAComponentRoot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PAComponentRoot();

            if (data.hasOwnProperty('data')) {
                obj['data'] = PAComponent.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PAComponent} data
 */
PAComponentRoot.prototype['data'] = undefined;

/**
 * @member {Object} meta
 */
PAComponentRoot.prototype['meta'] = undefined;






export default PAComponentRoot;

