/**
 * PA Engine API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: 3.16.0
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PACommentaryConfigurationSummary model module.
 * @module model/PACommentaryConfigurationSummary
 */
class PACommentaryConfigurationSummary {
    /**
     * Constructs a new <code>PACommentaryConfigurationSummary</code>.
     * @alias module:model/PACommentaryConfigurationSummary
     */
    constructor() { 
        
        PACommentaryConfigurationSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PACommentaryConfigurationSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PACommentaryConfigurationSummary} obj Optional instance to populate.
     * @return {module:model/PACommentaryConfigurationSummary} The populated <code>PACommentaryConfigurationSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PACommentaryConfigurationSummary();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('directory')) {
                obj['directory'] = ApiClient.convertToType(data['directory'], 'String');
            }
        }
        return obj;
    }


}

/**
 * PA commentary configuration name
 * @member {String} name
 */
PACommentaryConfigurationSummary.prototype['name'] = undefined;

/**
 * PA Commentary configuration directory
 * @member {String} directory
 */
PACommentaryConfigurationSummary.prototype['directory'] = undefined;






export default PACommentaryConfigurationSummary;

