# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from fds.sdk.FactSetFunds.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from fds.sdk.FactSetFunds.model.analytics_type import AnalyticsType
from fds.sdk.FactSetFunds.model.asset_allocation import AssetAllocation
from fds.sdk.FactSetFunds.model.asset_allocation_all_of import AssetAllocationAllOf
from fds.sdk.FactSetFunds.model.asset_allocation_type import AssetAllocationType
from fds.sdk.FactSetFunds.model.aum import Aum
from fds.sdk.FactSetFunds.model.aum_all_of import AumAllOf
from fds.sdk.FactSetFunds.model.aum_request import AumRequest
from fds.sdk.FactSetFunds.model.aum_request_data import AumRequestData
from fds.sdk.FactSetFunds.model.aum_response import AumResponse
from fds.sdk.FactSetFunds.model.benchmark_details import BenchmarkDetails
from fds.sdk.FactSetFunds.model.benchmark_details_all_of import BenchmarkDetailsAllOf
from fds.sdk.FactSetFunds.model.benchmark_details_type import BenchmarkDetailsType
from fds.sdk.FactSetFunds.model.classifications import Classifications
from fds.sdk.FactSetFunds.model.classifications_all_of import ClassificationsAllOf
from fds.sdk.FactSetFunds.model.classifications_type import ClassificationsType
from fds.sdk.FactSetFunds.model.content_set import ContentSet
from fds.sdk.FactSetFunds.model.content_set_item import ContentSetItem
from fds.sdk.FactSetFunds.model.content_sets_response import ContentSetsResponse
from fds.sdk.FactSetFunds.model.costs_fees import CostsFees
from fds.sdk.FactSetFunds.model.costs_fees_all_of import CostsFeesAllOf
from fds.sdk.FactSetFunds.model.costs_fees_request import CostsFeesRequest
from fds.sdk.FactSetFunds.model.costs_fees_request_data import CostsFeesRequestData
from fds.sdk.FactSetFunds.model.costs_fees_response import CostsFeesResponse
from fds.sdk.FactSetFunds.model.create_content_set_request import CreateContentSetRequest
from fds.sdk.FactSetFunds.model.create_content_set_request_body import CreateContentSetRequestBody
from fds.sdk.FactSetFunds.model.create_content_set_response import CreateContentSetResponse
from fds.sdk.FactSetFunds.model.create_content_set_response_data import CreateContentSetResponseData
from fds.sdk.FactSetFunds.model.create_request_field_object import CreateRequestFieldObject
from fds.sdk.FactSetFunds.model.credit_risk import CreditRisk
from fds.sdk.FactSetFunds.model.credit_risk_all_of import CreditRiskAllOf
from fds.sdk.FactSetFunds.model.credit_risk_type import CreditRiskType
from fds.sdk.FactSetFunds.model.criterion import Criterion
from fds.sdk.FactSetFunds.model.currency_response_field import CurrencyResponseField
from fds.sdk.FactSetFunds.model.custom_content_set_item import CustomContentSetItem
from fds.sdk.FactSetFunds.model.custom_content_sets import CustomContentSets
from fds.sdk.FactSetFunds.model.date_response_field import DateResponseField
from fds.sdk.FactSetFunds.model.dist_current import DistCurrent
from fds.sdk.FactSetFunds.model.dist_current_all_of import DistCurrentAllOf
from fds.sdk.FactSetFunds.model.dist_current_type import DistCurrentType
from fds.sdk.FactSetFunds.model.dist_historical import DistHistorical
from fds.sdk.FactSetFunds.model.dist_historical_all_of import DistHistoricalAllOf
from fds.sdk.FactSetFunds.model.dist_historical_type import DistHistoricalType
from fds.sdk.FactSetFunds.model.distinct_count_data import DistinctCountData
from fds.sdk.FactSetFunds.model.distinct_count_meta import DistinctCountMeta
from fds.sdk.FactSetFunds.model.distinct_count_request import DistinctCountRequest
from fds.sdk.FactSetFunds.model.distinct_count_request_body import DistinctCountRequestBody
from fds.sdk.FactSetFunds.model.distinct_count_response import DistinctCountResponse
from fds.sdk.FactSetFunds.model.distribution_type import DistributionType
from fds.sdk.FactSetFunds.model.distributions_item import DistributionsItem
from fds.sdk.FactSetFunds.model.distributions_request import DistributionsRequest
from fds.sdk.FactSetFunds.model.distributions_request_item import DistributionsRequestItem
from fds.sdk.FactSetFunds.model.distributions_response import DistributionsResponse
from fds.sdk.FactSetFunds.model.dividend_adjust import DividendAdjust
from fds.sdk.FactSetFunds.model.error_response import ErrorResponse
from fds.sdk.FactSetFunds.model.field import Field
from fds.sdk.FactSetFunds.model.field_response_object import FieldResponseObject
from fds.sdk.FactSetFunds.model.field_values import FieldValues
from fds.sdk.FactSetFunds.model.fields_response import FieldsResponse
from fds.sdk.FactSetFunds.model.filter import Filter
from fds.sdk.FactSetFunds.model.financials_key_items import FinancialsKeyItems
from fds.sdk.FactSetFunds.model.financials_key_items_request import FinancialsKeyItemsRequest
from fds.sdk.FactSetFunds.model.financials_key_items_request_data import FinancialsKeyItemsRequestData
from fds.sdk.FactSetFunds.model.financials_key_items_response import FinancialsKeyItemsResponse
from fds.sdk.FactSetFunds.model.flows import Flows
from fds.sdk.FactSetFunds.model.flows_all_of import FlowsAllOf
from fds.sdk.FactSetFunds.model.flows_request import FlowsRequest
from fds.sdk.FactSetFunds.model.flows_request_data import FlowsRequestData
from fds.sdk.FactSetFunds.model.flows_response import FlowsResponse
from fds.sdk.FactSetFunds.model.frequency import Frequency
from fds.sdk.FactSetFunds.model.frequency_aum import FrequencyAum
from fds.sdk.FactSetFunds.model.fund import Fund
from fds.sdk.FactSetFunds.model.fund_structure import FundStructure
from fds.sdk.FactSetFunds.model.fund_structure_all_of import FundStructureAllOf
from fds.sdk.FactSetFunds.model.fund_structure_type import FundStructureType
from fds.sdk.FactSetFunds.model.fund_vs_segment_benchmark import FundVsSegmentBenchmark
from fds.sdk.FactSetFunds.model.funds_error_object import FundsErrorObject
from fds.sdk.FactSetFunds.model.funds_error_object_source import FundsErrorObjectSource
from fds.sdk.FactSetFunds.model.funds_prices_request import FundsPricesRequest
from fds.sdk.FactSetFunds.model.funds_prices_request_data import FundsPricesRequestData
from fds.sdk.FactSetFunds.model.funds_prices_response import FundsPricesResponse
from fds.sdk.FactSetFunds.model.funds_returns_request import FundsReturnsRequest
from fds.sdk.FactSetFunds.model.funds_returns_request_data import FundsReturnsRequestData
from fds.sdk.FactSetFunds.model.funds_returns_response import FundsReturnsResponse
from fds.sdk.FactSetFunds.model.funds_returns_snapshot_request import FundsReturnsSnapshotRequest
from fds.sdk.FactSetFunds.model.funds_returns_snapshot_request_data import FundsReturnsSnapshotRequestData
from fds.sdk.FactSetFunds.model.funds_returns_snapshot_response import FundsReturnsSnapshotResponse
from fds.sdk.FactSetFunds.model.geographic_revenue import GeographicRevenue
from fds.sdk.FactSetFunds.model.geographic_revenue_all_of import GeographicRevenueAllOf
from fds.sdk.FactSetFunds.model.geographic_revenue_type import GeographicRevenueType
from fds.sdk.FactSetFunds.model.growth import Growth
from fds.sdk.FactSetFunds.model.growth_all_of import GrowthAllOf
from fds.sdk.FactSetFunds.model.growth_type import GrowthType
from fds.sdk.FactSetFunds.model.histogram_data import HistogramData
from fds.sdk.FactSetFunds.model.holdings import Holdings
from fds.sdk.FactSetFunds.model.identifier_response_fields import IdentifierResponseFields
from fds.sdk.FactSetFunds.model.ids import Ids
from fds.sdk.FactSetFunds.model.join_type import JoinType
from fds.sdk.FactSetFunds.model.key_items_type import KeyItemsType
from fds.sdk.FactSetFunds.model.lang import Lang
from fds.sdk.FactSetFunds.model.managers import Managers
from fds.sdk.FactSetFunds.model.margins import Margins
from fds.sdk.FactSetFunds.model.margins_all_of import MarginsAllOf
from fds.sdk.FactSetFunds.model.margins_type import MarginsType
from fds.sdk.FactSetFunds.model.market_capitalization import MarketCapitalization
from fds.sdk.FactSetFunds.model.market_capitalization_all_of import MarketCapitalizationAllOf
from fds.sdk.FactSetFunds.model.market_capitalization_type import MarketCapitalizationType
from fds.sdk.FactSetFunds.model.meta import Meta
from fds.sdk.FactSetFunds.model.meta_pagination import MetaPagination
from fds.sdk.FactSetFunds.model.meta_request import MetaRequest
from fds.sdk.FactSetFunds.model.nav_data_type import NavDataType
from fds.sdk.FactSetFunds.model.nested_field_value_object import NestedFieldValueObject
from fds.sdk.FactSetFunds.model.nested_field_values import NestedFieldValues
from fds.sdk.FactSetFunds.model.oas import OAS
from fds.sdk.FactSetFunds.model.operator import Operator
from fds.sdk.FactSetFunds.model.pagination import Pagination
from fds.sdk.FactSetFunds.model.pagination_request import PaginationRequest
from fds.sdk.FactSetFunds.model.per_share import PerShare
from fds.sdk.FactSetFunds.model.per_share_all_of import PerShareAllOf
from fds.sdk.FactSetFunds.model.per_share_type import PerShareType
from fds.sdk.FactSetFunds.model.portfolio_analytics_item import PortfolioAnalyticsItem
from fds.sdk.FactSetFunds.model.portfolio_analytics_request import PortfolioAnalyticsRequest
from fds.sdk.FactSetFunds.model.portfolio_analytics_request_data import PortfolioAnalyticsRequestData
from fds.sdk.FactSetFunds.model.portfolio_analytics_response import PortfolioAnalyticsResponse
from fds.sdk.FactSetFunds.model.portfolio_statistics import PortfolioStatistics
from fds.sdk.FactSetFunds.model.portfolio_statistics_all_of import PortfolioStatisticsAllOf
from fds.sdk.FactSetFunds.model.portfolio_statistics_request import PortfolioStatisticsRequest
from fds.sdk.FactSetFunds.model.portfolio_statistics_request_data import PortfolioStatisticsRequestData
from fds.sdk.FactSetFunds.model.portfolio_statistics_response import PortfolioStatisticsResponse
from fds.sdk.FactSetFunds.model.prices import Prices
from fds.sdk.FactSetFunds.model.prices_all_of import PricesAllOf
from fds.sdk.FactSetFunds.model.rate_risk import RateRisk
from fds.sdk.FactSetFunds.model.rate_risk_all_of import RateRiskAllOf
from fds.sdk.FactSetFunds.model.rate_risk_type import RateRiskType
from fds.sdk.FactSetFunds.model.ratios import Ratios
from fds.sdk.FactSetFunds.model.ratios_all_of import RatiosAllOf
from fds.sdk.FactSetFunds.model.ratios_type import RatiosType
from fds.sdk.FactSetFunds.model.regulations_tax_details import RegulationsTaxDetails
from fds.sdk.FactSetFunds.model.regulations_tax_details_all_of import RegulationsTaxDetailsAllOf
from fds.sdk.FactSetFunds.model.regulations_tax_details_type import RegulationsTaxDetailsType
from fds.sdk.FactSetFunds.model.returns import Returns
from fds.sdk.FactSetFunds.model.returns_all_of import ReturnsAllOf
from fds.sdk.FactSetFunds.model.returns_range import ReturnsRange
from fds.sdk.FactSetFunds.model.returns_range_all_of import ReturnsRangeAllOf
from fds.sdk.FactSetFunds.model.returns_range_request import ReturnsRangeRequest
from fds.sdk.FactSetFunds.model.returns_range_request_data import ReturnsRangeRequestData
from fds.sdk.FactSetFunds.model.returns_range_response import ReturnsRangeResponse
from fds.sdk.FactSetFunds.model.returns_snapshot import ReturnsSnapshot
from fds.sdk.FactSetFunds.model.returns_snapshot_all_of import ReturnsSnapshotAllOf
from fds.sdk.FactSetFunds.model.risk_analytics_item import RiskAnalyticsItem
from fds.sdk.FactSetFunds.model.risk_analytics_request import RiskAnalyticsRequest
from fds.sdk.FactSetFunds.model.risk_analytics_request_data import RiskAnalyticsRequestData
from fds.sdk.FactSetFunds.model.risk_analytics_response import RiskAnalyticsResponse
from fds.sdk.FactSetFunds.model.risk_measures import RiskMeasures
from fds.sdk.FactSetFunds.model.risk_measures_all_of import RiskMeasuresAllOf
from fds.sdk.FactSetFunds.model.risk_measures_type import RiskMeasuresType
from fds.sdk.FactSetFunds.model.risk_type import RiskType
from fds.sdk.FactSetFunds.model.scoring import Scoring
from fds.sdk.FactSetFunds.model.scoring_all_of import ScoringAllOf
from fds.sdk.FactSetFunds.model.scoring_request import ScoringRequest
from fds.sdk.FactSetFunds.model.scoring_request_data import ScoringRequestData
from fds.sdk.FactSetFunds.model.scoring_response import ScoringResponse
from fds.sdk.FactSetFunds.model.search_content_sets import SearchContentSets
from fds.sdk.FactSetFunds.model.search_criterion import SearchCriterion
from fds.sdk.FactSetFunds.model.search_data import SearchData
from fds.sdk.FactSetFunds.model.search_filter import SearchFilter
from fds.sdk.FactSetFunds.model.search_meta import SearchMeta
from fds.sdk.FactSetFunds.model.search_request import SearchRequest
from fds.sdk.FactSetFunds.model.search_request_body import SearchRequestBody
from fds.sdk.FactSetFunds.model.search_response import SearchResponse
from fds.sdk.FactSetFunds.model.sector_weightage import SectorWeightage
from fds.sdk.FactSetFunds.model.sector_weightage_all_of import SectorWeightageAllOf
from fds.sdk.FactSetFunds.model.sector_weightage_type import SectorWeightageType
from fds.sdk.FactSetFunds.model.segments_and_structure_item import SegmentsAndStructureItem
from fds.sdk.FactSetFunds.model.segments_and_structure_request import SegmentsAndStructureRequest
from fds.sdk.FactSetFunds.model.segments_and_structure_request_data import SegmentsAndStructureRequestData
from fds.sdk.FactSetFunds.model.segments_and_structure_response import SegmentsAndStructureResponse
from fds.sdk.FactSetFunds.model.similar_funds import SimilarFunds
from fds.sdk.FactSetFunds.model.similar_funds_all_of import SimilarFundsAllOf
from fds.sdk.FactSetFunds.model.similar_funds_type import SimilarFundsType
from fds.sdk.FactSetFunds.model.split_adjust import SplitAdjust
from fds.sdk.FactSetFunds.model.statistics_request import StatisticsRequest
from fds.sdk.FactSetFunds.model.statistics_request_body import StatisticsRequestBody
from fds.sdk.FactSetFunds.model.statistics_response import StatisticsResponse
from fds.sdk.FactSetFunds.model.statistics_response_data import StatisticsResponseData
from fds.sdk.FactSetFunds.model.structure_type import StructureType
from fds.sdk.FactSetFunds.model.summaries import Summaries
from fds.sdk.FactSetFunds.model.summaries_all_of import SummariesAllOf
from fds.sdk.FactSetFunds.model.summaries_request import SummariesRequest
from fds.sdk.FactSetFunds.model.summaries_request_data import SummariesRequestData
from fds.sdk.FactSetFunds.model.summaries_response import SummariesResponse
from fds.sdk.FactSetFunds.model.tax_exposure import TaxExposure
from fds.sdk.FactSetFunds.model.tax_exposure_all_of import TaxExposureAllOf
from fds.sdk.FactSetFunds.model.tax_exposure_type import TaxExposureType
from fds.sdk.FactSetFunds.model.tax_items_type import TaxItemsType
from fds.sdk.FactSetFunds.model.taxes_and_risks_item import TaxesAndRisksItem
from fds.sdk.FactSetFunds.model.taxes_and_risks_request import TaxesAndRisksRequest
from fds.sdk.FactSetFunds.model.taxes_and_risks_request_data import TaxesAndRisksRequestData
from fds.sdk.FactSetFunds.model.taxes_and_risks_response import TaxesAndRisksResponse
from fds.sdk.FactSetFunds.model.top_holdings import TopHoldings
from fds.sdk.FactSetFunds.model.top_holdings_all_of import TopHoldingsAllOf
from fds.sdk.FactSetFunds.model.top_holdings_request import TopHoldingsRequest
from fds.sdk.FactSetFunds.model.top_holdings_request_data import TopHoldingsRequestData
from fds.sdk.FactSetFunds.model.top_holdings_response import TopHoldingsResponse
from fds.sdk.FactSetFunds.model.trading import Trading
from fds.sdk.FactSetFunds.model.trading_all_of import TradingAllOf
from fds.sdk.FactSetFunds.model.trading_request import TradingRequest
from fds.sdk.FactSetFunds.model.trading_response import TradingResponse
from fds.sdk.FactSetFunds.model.wal import WAL
from fds.sdk.FactSetFunds.model.yields import Yields
from fds.sdk.FactSetFunds.model.yields_all_of import YieldsAllOf
from fds.sdk.FactSetFunds.model.yields_request import YieldsRequest
from fds.sdk.FactSetFunds.model.yields_request_data import YieldsRequestData
from fds.sdk.FactSetFunds.model.yields_response import YieldsResponse
