# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from fds.sdk.OPENOPTIMIZER.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from fds.sdk.OPENOPTIMIZER.model.afi_account_input import AFIAccountInput
from fds.sdk.OPENOPTIMIZER.model.afi_optimization_parameters import AFIOptimizationParameters
from fds.sdk.OPENOPTIMIZER.model.afi_optimization_parameters_request import AFIOptimizationParametersRequest
from fds.sdk.OPENOPTIMIZER.model.afi_optimizer_strategy_input import AFIOptimizerStrategyInput
from fds.sdk.OPENOPTIMIZER.model.afi_optimizer_strategy_overrides_input import AFIOptimizerStrategyOverridesInput
from fds.sdk.OPENOPTIMIZER.model.axp_account_input import AXPAccountInput
from fds.sdk.OPENOPTIMIZER.model.axp_available_components_input import AXPAvailableComponentsInput
from fds.sdk.OPENOPTIMIZER.model.axp_available_components_input_data import AXPAvailableComponentsInputData
from fds.sdk.OPENOPTIMIZER.model.axp_available_components_input_data_filters import AXPAvailableComponentsInputDataFilters
from fds.sdk.OPENOPTIMIZER.model.axp_available_components_input_data_filters_constraints import AXPAvailableComponentsInputDataFiltersConstraints
from fds.sdk.OPENOPTIMIZER.model.axp_available_components_input_data_filters_objectives import AXPAvailableComponentsInputDataFiltersObjectives
from fds.sdk.OPENOPTIMIZER.model.axp_optimization_parameters import AXPOptimizationParameters
from fds.sdk.OPENOPTIMIZER.model.axp_optimization_parameters_request import AXPOptimizationParametersRequest
from fds.sdk.OPENOPTIMIZER.model.axp_optimizer_strategy_input import AXPOptimizerStrategyInput
from fds.sdk.OPENOPTIMIZER.model.axp_optimizer_strategy_overrides_input import AXPOptimizerStrategyOverridesInput
from fds.sdk.OPENOPTIMIZER.model.archive_portfolio_output_type import ArchivePortfolioOutputType
from fds.sdk.OPENOPTIMIZER.model.available_components_response import AvailableComponentsResponse
from fds.sdk.OPENOPTIMIZER.model.available_components_response_data import AvailableComponentsResponseData
from fds.sdk.OPENOPTIMIZER.model.available_constraints_result_object import AvailableConstraintsResultObject
from fds.sdk.OPENOPTIMIZER.model.available_constraints_result_object_data import AvailableConstraintsResultObjectData
from fds.sdk.OPENOPTIMIZER.model.available_objectives_object import AvailableObjectivesObject
from fds.sdk.OPENOPTIMIZER.model.available_strategies_input import AvailableStrategiesInput
from fds.sdk.OPENOPTIMIZER.model.available_strategies_input_data import AvailableStrategiesInputData
from fds.sdk.OPENOPTIMIZER.model.available_strategies_response import AvailableStrategiesResponse
from fds.sdk.OPENOPTIMIZER.model.available_terms_object import AvailableTermsObject
from fds.sdk.OPENOPTIMIZER.model.available_transcosts_result_object import AvailableTranscostsResultObject
from fds.sdk.OPENOPTIMIZER.model.available_transcosts_result_object_data import AvailableTranscostsResultObjectData
from fds.sdk.OPENOPTIMIZER.model.bpm_account_input import BPMAccountInput
from fds.sdk.OPENOPTIMIZER.model.bpmnpo_available_components_input import BPMNPOAvailableComponentsInput
from fds.sdk.OPENOPTIMIZER.model.bpmnpo_available_components_input_data import BPMNPOAvailableComponentsInputData
from fds.sdk.OPENOPTIMIZER.model.bpm_optimization_parameters import BPMOptimizationParameters
from fds.sdk.OPENOPTIMIZER.model.bpm_optimization_parameters_request import BPMOptimizationParametersRequest
from fds.sdk.OPENOPTIMIZER.model.bpm_optimizer_strategy_input import BPMOptimizerStrategyInput
from fds.sdk.OPENOPTIMIZER.model.bpm_optimizer_strategy_overrides_input import BPMOptimizerStrategyOverridesInput
from fds.sdk.OPENOPTIMIZER.model.client_error_response import ClientErrorResponse
from fds.sdk.OPENOPTIMIZER.model.constraints import Constraints
from fds.sdk.OPENOPTIMIZER.model.enabled_enum import EnabledEnum
from fds.sdk.OPENOPTIMIZER.model.error import Error
from fds.sdk.OPENOPTIMIZER.model.error_detail import ErrorDetail
from fds.sdk.OPENOPTIMIZER.model.fpo_account_input import FPOAccountInput
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input import FPOAvailableComponentsInput
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data import FPOAvailableComponentsInputData
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data_document_level import FPOAvailableComponentsInputDataDocumentLevel
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data_filters import FPOAvailableComponentsInputDataFilters
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data_filters_constraints import FPOAvailableComponentsInputDataFiltersConstraints
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data_filters_objectives import FPOAvailableComponentsInputDataFiltersObjectives
from fds.sdk.OPENOPTIMIZER.model.fpo_available_components_input_data_filters_transaction_costs import FPOAvailableComponentsInputDataFiltersTransactionCosts
from fds.sdk.OPENOPTIMIZER.model.fpo_objective_input import FPOObjectiveInput
from fds.sdk.OPENOPTIMIZER.model.fpo_optimization_parameters import FPOOptimizationParameters
from fds.sdk.OPENOPTIMIZER.model.fpo_optimization_parameters_request import FPOOptimizationParametersRequest
from fds.sdk.OPENOPTIMIZER.model.fpo_optimizer_strategy_input import FPOOptimizerStrategyInput
from fds.sdk.OPENOPTIMIZER.model.fpo_optimizer_strategy_overrides_input import FPOOptimizerStrategyOverridesInput
from fds.sdk.OPENOPTIMIZER.model.holdings_response_object import HoldingsResponseObject
from fds.sdk.OPENOPTIMIZER.model.npo_account_input import NPOAccountInput
from fds.sdk.OPENOPTIMIZER.model.npo_optimization_parameters import NPOOptimizationParameters
from fds.sdk.OPENOPTIMIZER.model.npo_optimization_parameters_request import NPOOptimizationParametersRequest
from fds.sdk.OPENOPTIMIZER.model.npo_optimizer_strategy_input import NPOOptimizerStrategyInput
from fds.sdk.OPENOPTIMIZER.model.npo_optimizer_strategy_overrides_input import NPOOptimizerStrategyOverridesInput
from fds.sdk.OPENOPTIMIZER.model.optimal_holdings_output_type import OptimalHoldingsOutputType
from fds.sdk.OPENOPTIMIZER.model.optimization_input import OptimizationInput
from fds.sdk.OPENOPTIMIZER.model.optimization_status import OptimizationStatus
from fds.sdk.OPENOPTIMIZER.model.optimization_status_data import OptimizationStatusData
from fds.sdk.OPENOPTIMIZER.model.optimizer_account_overrides_input import OptimizerAccountOverridesInput
from fds.sdk.OPENOPTIMIZER.model.optimizer_output_types import OptimizerOutputTypes
from fds.sdk.OPENOPTIMIZER.model.optimizer_reports_output_type import OptimizerReportsOutputType
from fds.sdk.OPENOPTIMIZER.model.pa_doc_input import PaDocInput
from fds.sdk.OPENOPTIMIZER.model.report_output_type_object import ReportOutputTypeObject
from fds.sdk.OPENOPTIMIZER.model.result_response import ResultResponse
from fds.sdk.OPENOPTIMIZER.model.result_response_data import ResultResponseData
from fds.sdk.OPENOPTIMIZER.model.result_response_data_archive import ResultResponseDataArchive
from fds.sdk.OPENOPTIMIZER.model.result_response_data_debug_file import ResultResponseDataDebugFile
from fds.sdk.OPENOPTIMIZER.model.result_response_data_debug_file_input import ResultResponseDataDebugFileInput
from fds.sdk.OPENOPTIMIZER.model.result_response_data_reports import ResultResponseDataReports
from fds.sdk.OPENOPTIMIZER.model.result_response_data_stats import ResultResponseDataStats
from fds.sdk.OPENOPTIMIZER.model.settings_global_vars_response import SettingsGlobalVarsResponse
from fds.sdk.OPENOPTIMIZER.model.stat_response_object import StatResponseObject
from fds.sdk.OPENOPTIMIZER.model.trade_response_object import TradeResponseObject
from fds.sdk.OPENOPTIMIZER.model.trades_list_output_type import TradesListOutputType
