/**
 * Universal Screening API
 * Through the Universal Screening API, you can access the power of FactSet's Universal Screening Application. Calculate and return the results of your saved Universal Screens.
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubmitExportResponseData from './SubmitExportResponseData';

/**
 * The SubmitExportResponse model module.
 * @module model/SubmitExportResponse
 */
class SubmitExportResponse {
    /**
     * Constructs a new <code>SubmitExportResponse</code>.
     * SubmitExportResponse contains information regarding the start of a long-running export job.
     * @alias module:model/SubmitExportResponse
     */
    constructor() { 
        
        SubmitExportResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubmitExportResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitExportResponse} obj Optional instance to populate.
     * @return {module:model/SubmitExportResponse} The populated <code>SubmitExportResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitExportResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = SubmitExportResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SubmitExportResponseData} data
 */
SubmitExportResponse.prototype['data'] = undefined;






export default SubmitExportResponse;

