# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from fds.sdk.RecommendationListAPIforDigitalPortals.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from fds.sdk.RecommendationListAPIforDigitalPortals.model.attributes_member import AttributesMember
from fds.sdk.RecommendationListAPIforDigitalPortals.model.cursor_based_pagination_output_object import CursorBasedPaginationOutputObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.cursor_based_pagination_output_object_without_total import CursorBasedPaginationOutputObjectWithoutTotal
from fds.sdk.RecommendationListAPIforDigitalPortals.model.error_meta_object import ErrorMetaObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.error_object import ErrorObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_object import InlineObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200 import InlineResponse200
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2001 import InlineResponse2001
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2001_active_range import InlineResponse2001ActiveRange
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2001_data import InlineResponse2001Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2002 import InlineResponse2002
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2002_data import InlineResponse2002Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2002_data_instrument import InlineResponse2002DataInstrument
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2002_data_recommendation_list import InlineResponse2002DataRecommendationList
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2002_data_types import InlineResponse2002DataTypes
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2003 import InlineResponse2003
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2003_data import InlineResponse2003Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2004 import InlineResponse2004
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2004_data import InlineResponse2004Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005 import InlineResponse2005
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_data import InlineResponse2005Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_description import InlineResponse2005Description
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_notation import InlineResponse2005Notation
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_notation_instrument import InlineResponse2005NotationInstrument
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_notation_instrument_type import InlineResponse2005NotationInstrumentType
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_notation_market import InlineResponse2005NotationMarket
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response2005_recommendation_class import InlineResponse2005RecommendationClass
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200_data import InlineResponse200Data
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200_data_active_range import InlineResponse200DataActiveRange
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200_data_active_revision import InlineResponse200DataActiveRevision
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200_data_active_revision_active_range import InlineResponse200DataActiveRevisionActiveRange
from fds.sdk.RecommendationListAPIforDigitalPortals.model.inline_response200_meta import InlineResponse200Meta
from fds.sdk.RecommendationListAPIforDigitalPortals.model.language_member import LanguageMember
from fds.sdk.RecommendationListAPIforDigitalPortals.model.offset_based_pagination_output_object import OffsetBasedPaginationOutputObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.offset_based_pagination_output_object_without_total import OffsetBasedPaginationOutputObjectWithoutTotal
from fds.sdk.RecommendationListAPIforDigitalPortals.model.partial_output_object import PartialOutputObject
from fds.sdk.RecommendationListAPIforDigitalPortals.model.recommendation_list_revision_list_data import RecommendationListRevisionListData
from fds.sdk.RecommendationListAPIforDigitalPortals.model.recommendation_list_revision_list_data_active_range import RecommendationListRevisionListDataActiveRange
from fds.sdk.RecommendationListAPIforDigitalPortals.model.recommendation_list_revision_list_meta import RecommendationListRevisionListMeta
from fds.sdk.RecommendationListAPIforDigitalPortals.model.status_object import StatusObject
