/**
 * Prime Developer Trial
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2005DataEstimatesFirstFiscalYearCurrencyDependentEstimatesEbitMean from './InlineResponse2005DataEstimatesFirstFiscalYearCurrencyDependentEstimatesEbitMean';

/**
 * The InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets model module.
 * @module model/InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets
 * @version 0.9.1
 */
class InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets {
    /**
     * Constructs a new <code>InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets</code>.
     * Return on assets (ROA), which is the ratio of the net income, divided by the total assets.
     * @alias module:model/InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets
     */
    constructor() { 
        
        InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets} obj Optional instance to populate.
     * @return {module:model/InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets} The populated <code>InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets();

            if (data.hasOwnProperty('mean')) {
                obj['mean'] = InlineResponse2005DataEstimatesFirstFiscalYearCurrencyDependentEstimatesEbitMean.constructFromObject(data['mean']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse2005DataEstimatesFirstFiscalYearCurrencyDependentEstimatesEbitMean} mean
 */
InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets.prototype['mean'] = undefined;






export default InlineResponse2005DataEstimatesFirstFiscalYearReturnOnAssets;

