# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from fds.sdk.IRNConfiguration.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from fds.sdk.IRNConfiguration.model.approval_level_config_dto import ApprovalLevelConfigDto
from fds.sdk.IRNConfiguration.model.approval_process_config_dto import ApprovalProcessConfigDto
from fds.sdk.IRNConfiguration.model.author_config_dto import AuthorConfigDto
from fds.sdk.IRNConfiguration.model.client_sales_representative_dto import ClientSalesRepresentativeDto
from fds.sdk.IRNConfiguration.model.commentary_config_dto import CommentaryConfigDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_dto import ContactCustomFieldDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_formula_dto import ContactCustomFieldFormulaDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_option_dto import ContactCustomFieldOptionDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_option_save_dto import ContactCustomFieldOptionSaveDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_save_dto import ContactCustomFieldSaveDto
from fds.sdk.IRNConfiguration.model.contact_custom_field_type import ContactCustomFieldType
from fds.sdk.IRNConfiguration.model.contact_role_dto import ContactRoleDto
from fds.sdk.IRNConfiguration.model.contact_type_dto import ContactTypeDto
from fds.sdk.IRNConfiguration.model.create_custom_symbol_custom_field_dto import CreateCustomSymbolCustomFieldDto
from fds.sdk.IRNConfiguration.model.custom_field_config_dto import CustomFieldConfigDto
from fds.sdk.IRNConfiguration.model.custom_symbol_custom_field_config_dto import CustomSymbolCustomFieldConfigDto
from fds.sdk.IRNConfiguration.model.custom_symbol_custom_field_formula_config_dto import CustomSymbolCustomFieldFormulaConfigDto
from fds.sdk.IRNConfiguration.model.custom_symbol_sub_type_dto import CustomSymbolSubTypeDto
from fds.sdk.IRNConfiguration.model.custom_symbol_type_detail_dto import CustomSymbolTypeDetailDto
from fds.sdk.IRNConfiguration.model.custom_symbol_type_dto import CustomSymbolTypeDto
from fds.sdk.IRNConfiguration.model.custom_symbol_type_summary_dto import CustomSymbolTypeSummaryDto
from fds.sdk.IRNConfiguration.model.date_settings_dto import DateSettingsDto
from fds.sdk.IRNConfiguration.model.entity_type import EntityType
from fds.sdk.IRNConfiguration.model.extended_text_config_dto import ExtendedTextConfigDto
from fds.sdk.IRNConfiguration.model.formula_config_dto import FormulaConfigDto
from fds.sdk.IRNConfiguration.model.group_config_dto import GroupConfigDto
from fds.sdk.IRNConfiguration.model.group_fields_dto import GroupFieldsDto
from fds.sdk.IRNConfiguration.model.headline_format_config_dto import HeadlineFormatConfigDto
from fds.sdk.IRNConfiguration.model.identifier_settings_dto import IdentifierSettingsDto
from fds.sdk.IRNConfiguration.model.integer_config_dto import IntegerConfigDto
from fds.sdk.IRNConfiguration.model.link_settings_dto import LinkSettingsDto
from fds.sdk.IRNConfiguration.model.new_item_dto import NewItemDto
from fds.sdk.IRNConfiguration.model.note_settings_dto import NoteSettingsDto
from fds.sdk.IRNConfiguration.model.numeric_config_dto import NumericConfigDto
from fds.sdk.IRNConfiguration.model.operation import Operation
from fds.sdk.IRNConfiguration.model.operation_type import OperationType
from fds.sdk.IRNConfiguration.model.options_config_dto import OptionsConfigDto
from fds.sdk.IRNConfiguration.model.organizer_settings_dto import OrganizerSettingsDto
from fds.sdk.IRNConfiguration.model.phone_number_type_dto import PhoneNumberTypeDto
from fds.sdk.IRNConfiguration.model.problem_details import ProblemDetails
from fds.sdk.IRNConfiguration.model.rating_config_dto import RatingConfigDto
from fds.sdk.IRNConfiguration.model.recommendation_config_dto import RecommendationConfigDto
from fds.sdk.IRNConfiguration.model.recommendation_settings_dto import RecommendationSettingsDto
from fds.sdk.IRNConfiguration.model.related_contacts_settings_dto import RelatedContactsSettingsDto
from fds.sdk.IRNConfiguration.model.related_research_settings_dto import RelatedResearchSettingsDto
from fds.sdk.IRNConfiguration.model.related_symbols_settings_dto import RelatedSymbolsSettingsDto
from fds.sdk.IRNConfiguration.model.relationship_category_dto import RelationshipCategoryDto
from fds.sdk.IRNConfiguration.model.relationship_category_list_dto import RelationshipCategoryListDto
from fds.sdk.IRNConfiguration.model.relationship_category_save_dto import RelationshipCategorySaveDto
from fds.sdk.IRNConfiguration.model.relationship_dto import RelationshipDto
from fds.sdk.IRNConfiguration.model.relationship_save_dto import RelationshipSaveDto
from fds.sdk.IRNConfiguration.model.relationship_type import RelationshipType
from fds.sdk.IRNConfiguration.model.reorder_custom_symbol_type_dto import ReorderCustomSymbolTypeDto
from fds.sdk.IRNConfiguration.model.save_custom_symbol_type_dto import SaveCustomSymbolTypeDto
from fds.sdk.IRNConfiguration.model.sentiment_config_dto import SentimentConfigDto
from fds.sdk.IRNConfiguration.model.sentiment_settings_dto import SentimentSettingsDto
from fds.sdk.IRNConfiguration.model.source_settings_dto import SourceSettingsDto
from fds.sdk.IRNConfiguration.model.subject_config_dto import SubjectConfigDto
from fds.sdk.IRNConfiguration.model.subject_settings_dto import SubjectSettingsDto
from fds.sdk.IRNConfiguration.model.subject_summary_dto import SubjectSummaryDto
from fds.sdk.IRNConfiguration.model.symbols_relation_ship_save_dto import SymbolsRelationShipSaveDto
from fds.sdk.IRNConfiguration.model.symbols_relationship_dto import SymbolsRelationshipDto
from fds.sdk.IRNConfiguration.model.team_config_dto import TeamConfigDto
from fds.sdk.IRNConfiguration.model.team_settings_dto import TeamSettingsDto
from fds.sdk.IRNConfiguration.model.team_summary_dto import TeamSummaryDto
from fds.sdk.IRNConfiguration.model.title_settings_dto import TitleSettingsDto
from fds.sdk.IRNConfiguration.model.update_custom_symbol_type_dto import UpdateCustomSymbolTypeDto
from fds.sdk.IRNConfiguration.model.user_config_dto import UserConfigDto
